darshan-hpc/darshan

darshan-runtime/configure.in
=> autoconf const checks should fail on warnings

ChangeLog, darshan-runtime/Makefile.in
Fixes #399
Marked as WIP until trying a few test cases on Theta.
=> add explicit lustreapi library dependency

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/templates/summary.html
changes for summarizing APMPI from Darshan into new job summary report
=> pydarshan: new APMPI stats in a html report generation

darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py, darshan-util/pydarshan/tests/test_heatmap_handling.py, darshan-util/pydarshan/tests/test_plot_dxt_heatmap.py
* address the changes I asked for when
merging gh-396
=> MAINT: changes requested for heatmap

darshan-util/pydarshan/benchmarks/asv.conf.json, darshan-util/pydarshan/benchmarks/benchmarks/dxt_heatmap.py, darshan-util/pydarshan/examples/example-logs/__init__.py, darshan-util/pydarshan/setup.py, darshan-util/pydarshan/tests/input/__init__.py
Related to #426 -- add some example `asv` benchmark infrastructure that the team can build upon. Includes a few tricky packaging/module-related changes to make the data files available for benchmarking.
On this feature branch the output of `asv run` is below. The overarching purpose is to allow more formal/statistically significant assessment of claims of performance improvement for changes in the Python code base (with i.e., `asv continuous` for comparing two commit hashes/branches).
One thing to be cautious of is changes to the C code underneath--as I understand it, the `setup.py` build doesn't currently link in the `darshan-util` C deps automatically as part of the build procedure--if that were to change, we could also detect perf improvements underneath the hood if they span two …
=> WIP, BENCH: start asv infrastructure

darshan-util/pydarshan/mypy.ini, darshan-util/pydarshan/tests/conftest.py
* first part of gh-460; add `conftest.py` file
to set the `has_log_repo` variable for our testing
infrastructure
* I also want something straightforward to merge
to start probing the `codecov` app infrastructure @shanedsnyder 
just set up
=> TST, MAINT: add conftest.py for logs

darshan-runtime/share/ld-opts/Makefile.am
=> add base-ld-opts to EXTRA_DIST

darshan-util/pydarshan/tests/test_report.py
Added two new tests to tests/test_report.py to improve code
coverage. Resolves Issue #457
=> Report.py Coverage

darshan-util/pydarshan/darshan/cli/summary.py
* Remove `dtype="pandas"` argument from
`DarshanReport` call in summary.py
* Fix gh-493
=> MAINT: Remove data type specifier from DarshanReport call

.github/workflows/main_ci.yml
Modify the CI action to use an out-of-tree build for darshan-util.
=> use out-of-tree build for darshan-util

darshan-util/pydarshan/benchmarks/benchmarks/report.py
* Add benchmark for `to_df` method of `DarshanRecordCollection`
* Contributes to #529
=> BENCH: Add benchmark for `DarshanRecordCollection.to_df()`

darshan-util/pydarshan/tests/test_report.py
* Add a unit test for `DarshanRecordCollection.to_df()` to
increase confidence in performance optimizations
=> TST: Add test for `DarshanRecordCollection.to_df()`

darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py
=> MAINT: Remove heatmap figure title

darshan-util/pydarshan/darshan/report.py, darshan-util/pydarshan/tests/test_report.py
* Add code path to allow for converting `LUSTRE`
module data into `pandas` dataframes
* Fix issue #543
=> ENH: Add `LUSTRE` module support to `DarshanRecordCollection.to_df()`

darshan-util/pydarshan/darshan/report.py
* Leverage pandas to remove loops over generic
darshan records and improve performance
* Change "attach" parameter to insert columns into
dataframes instead of flipping columns back/forth
* Change `LUSTRE` code to use `to_numpy()`
for small performance improvement
* Remove unnecessary `enumerate` for `DXT` records
* Fixes issue #529
=> ENH: optimize `DarshanRecordCollection.to_df()`

darshan-util/pydarshan/darshan/cli/summary.py
* Remove f-string from `register_figures()` documentation
* Small whitespace fix
=> MAINT: cleanup of `summary.py`

darshan-util/pydarshan/darshan/experimental/plots/plot_access_histogram.py
* Remove unnecessary imports
* Move title into x-axis label
* Reformat longer lines to reduce length
* Simplify data handling code
* Contributes to #577
=> MAINT: Cleanup `plot_access_histogram.py`

darshan-util/pydarshan/darshan/experimental/plots/plot_opcounts.py
* Contributes to #569
* Remove figure title
* Remove unused `as_csv` function
* Remove commented out code
* Remove unused imports
* Reduce line width of long print statement
=> MAINT: Cleanup `plot_opcounts.py`

darshan-util/pydarshan/darshan/experimental/plots/plot_opcounts.py
* Abstract data handling code into new function `gather_count_data`
* Move `autolabel` function outside of `plot_opcounts`
* Add `ax` parameter to `autolabel` and correct call signatures
* Related to issue #569
=> MAINT: Refactor `plot_opcounts.py`

darshan-util/pydarshan/mypy.ini, darshan-util/pydarshan/tests/test_plot_io_cost.py, darshan-util/pydarshan/tests/test_report.py, darshan-util/pydarshan/tests/test_summary.py
* Change mypy pandas config to ignore all imports
* Remove unnecessary type ignores for `pandas.testing` imports
=> MAINT: Update mypy config to ignore all pandas imports

darshan-util/pydarshan/darshan/experimental/plots/plot_common_access_table.py, darshan-util/pydarshan/tests/test_plot_common_access_table.py
* Add module `plot_common_access_table.py` for
generating the per-module common access table
* Add testing module `test_plot_common_access_table.py`
with unit tests for each function in
`plot_common_access_table.py`
* Add figure 4.) in #465
=> ENH: Add common access table

darshan-util/pydarshan/tests/test_plot_common_access_table.py
* Minor cleanup for gh-600 -- addresses @treddy's [comment](https://github.com/darshan-hpc/darshan/pull/600#issuecomment-1008458846)
=> MAINT: PR 600 cleanup, remove unused import in `test_plot_common_access_table.py`

darshan-util/pydarshan/darshan/experimental/plots/plot_common_access_table.py
* Update return type for `plot_common_access_table` from
generic `Any` to `DarshanReportTable`
=> MAINT: Update return type for `plot_common_access_table`

darshan-util/pydarshan/darshan/tests/test_summary.py
* Fix comment in `test_module_table()`
=> MAINT: PR 634 cleanup

darshan-util/pydarshan/darshan/cli/base.html
=> ENH: Add Darshan website link to summary report footer

darshan-util/pydarshan/darshan/cli/summary.py
* Update captions for DXT heat map, I/O cost, and Access Size
figures according to suggestions from Phil
* Contributes to issue #641
=> ENH: Update summary report figure captions

darshan-runtime/lib/darshan-heatmap.c
- all histograms emitted in a given job will now have the same bin width and number of bins
Fixes #672
=> normalize heatmap histograms

darshan-runtime/configure.ac, darshan-runtime/lib/Makefile.am, darshan-runtime/lib/darshan-heatmap.h
--disable-dxt option and corresponding build changes
Fixes #620
=> ability to disable heatmap at compile time

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* Fix issue #717
* Add regression test `test_issue_717`
=> BUG, TST: Fix issue 717

.github/workflows/runtime_ci.yml, .gitignore, darshan-test/c_mpi_progs/runtime_prog_issue_730.c, darshan-test/python_mpi_scripts/runtime_prog_issue_690.py, darshan-test/python_runtime_tests.py
* this builds on the new testing infrastructure drafted in gh-753, which should be
reviewed/dealt with before this PR
* add a C-language regression test based on Phil's comment here:
https://github.com/darshan-hpc/darshan/pull/737#issuecomment-1126148539
* at the time of writing, however, the test passes--there is no evidence of
overflow--I'm open to suggestions from the "C folks" on the team..
=> WIP, TST: Regression test for runtime integer overflow in HEATMAP

darshan-util/pydarshan/darshan/tests/test_summary.py
* `test_main_all_logs_repo_files()` has been adjusted
to allow the testsuite to pass when the additional logs
from https://github.com/darshan-hpc/darshan-logs/pull/39
are included
* in short, when the log minor version is greater than or equal to `4`,
we need to account for the default presence of the runtime
`HEATMAP` module; if the major version ever bumps from `3`
to `4` we'll need some more shims, but perhaps that can be
deferred for now
* for completeness, I checked that the adjusted test + new logs
correctly detect a regression when gh-764 is reverted:
```
FAILED tests/test_report.py::test_jobid_type_all_logs_repo_files[/Users/treddy/python_venvs/python_395_darshan/lib/python3.9/site-packages/darshan_logs/release_logs/mpi-io-test-x86_64-3.0.0.darshan]
FAILED …
```
=> TST: shims for new logs

darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py
* apply the faster interpolation algorithm
described at:
https://github.com/darshan-hpc/darshan/issues/798#issuecomment-1226383841
* as I note in the source, this could likely be even
faster if we used Cython or numba, but I decided against
the complexity of a new build or runtime dependency just yet..
* this also has the advantage of removing a version
switch for Python (which actually should have been
a version switch for `pandas`)
* the HTML report generation time for `e3sm_io_heatmap_and_dxt.darshan` drops from `47` to `33` seconds on my machine, while the `snyder_acme..` log timing remains unchaged (dominated by "data ingestion" there); also, our internal benchmark suite shows this branch as decisively faster than `main`, so I don't really see a drawback:
`asv continuous -e -b …
=> ENH: faster DXT interpolation

darshan-runtime/lib/Makefile.am
Fix for #841 
Also see 237ab5e6ee4deca11054a714063e0029059ac1f3
=> remove unused file darshan-core.h

ChangeLog, configure.ac, darshan-runtime/configure.ac, darshan-test/RELEASE-CHECKLIST.txt, darshan-util/configure.ac, darshan-util/pydarshan/CHANGELOG.rst, darshan-util/pydarshan/darshan/__init__.py, darshan-util/pydarshan/setup.cfg, darshan-util/pydarshan/setup.py
Includes:
- darshan/PyDarshan changelog updates
- updated various darshan/PyDarshan version numbers
- small simplification to release checklist
=> 3.4.1 release prep

ChangeLog, configure.ac, darshan-runtime/configure.ac, darshan-util/configure.ac, darshan-util/pydarshan/CHANGELOG.rst, darshan-util/pydarshan/darshan/__init__.py, darshan-util/pydarshan/setup.cfg, darshan-util/pydarshan/setup.py
Updated Changelogs and package versions for 3.4.2 release
=> 3.4.2 release prep

.github/workflows/runtime_ci.yml
* try to circumvent gh-895 for now
=> CI: setuptools pin for runtime job

darshan-util/pydarshan/darshan/cli/file_stats.py
- Added performance metrics to file_stats, including: I/O Bandwidth by slowest, I/O time by slowest, and total bytes. 
- Added sorting by the new metrics
- Reformatted the code of file_stats.py for better readability.
=> Added I/O performance metrics to file_stats

darshan-runtime/test/Makefile.am, darshan-runtime/test/tst_runs.sh, darshan-test/regression/test-cases/src/fprintf-fscanf-test.c
Some minor issues found when running `make distcheck` using
various configure options, i.e. with/without MPI, with/without darshan-util, etc.
=> Minor fixes
