darshan-hpc/darshan

darshan-util/darshan-job-summary/bin/darshan-job-summary.pl.in
Reported by Jeff Layton (see https://lists.mcs.anl.gov/pipermail/darshan-users/2021-June/000693.html).  There was a bug in logic added to darshan-job-summary.pl to filter out negative mmap counter values; it did not account for situations in which the counter was not present at all (i.e., the POSIX module was not activated).
=> fix undefined var if POSIX module not active

.github/workflows/linux.yml
Fixes #407
* add basic CI testing for `pydarshan` with the three most recent stable versions of Python on Linux; only applies to PRs to `pydarshan-devel` branch for now, which is probably fine
* there are various additional settings/static analyses/test matrix entries and so on that we'll likely want to add over time, but this basic CI setup seems to work just fine already when [tested on my fork](https://github.com/tylerjereddy/darshan/pull/1)
=> CI: add basic Python CI for pydarshan-devel

darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py, darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py, darshan-util/pydarshan/setup.py, darshan-util/pydarshan/tests/test_heatmap_handling.py, darshan-util/pydarshan/tests/test_plot_dxt_heatmap.py
DXT heatmap plotting code for potential use in updated job summary. Primarily uses `numpy`, `seaborn`, `matplotlib` for plotting, which are all pip installable.  
Summary
---------
At the moment it takes in logs with `DXT_POSIX` data, concatenates all of the read/write segment dataframes together,  then uses that data (along with the respective rank data) to create a 2D histogram, and plot a heat map with marginal bar graphs. Depending on which operations you include, it will plot only the `read` segment data, the `write` segment data, or both. It does not distinguish between operations. Each bin (in the heatmap) is populated with the data sum and/or proportionate data sum for all IO events read/written during the time spanned by the bin.The color bar was selected based on the fact that …
=> WIP: PyDarshan: Adds heatmap plotting code for DXT tracing logs

.github/workflows/linux.yml, darshan-util/pydarshan/darshan/__init__.py, darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py, darshan-util/pydarshan/mypy.ini
Fixes #418
* add a basic `mypy.ini` config file, based on
similar type checking config files in other Python
OSS projects (to keep type checking consistent on the
project)
* add type checking to CI matrix
* fix a few minor typing issues in the source
to get `mypy` passing
=> MAINT, CI: add mypy to CI

darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py
* the `to_df()` call in `get_single_df_dict()` does not
appear to serve any purpose, so remove it
* the change was performance agnostic using the heatmap
benchmarks in gh-428 
(mostly dominated by `seaborn` stuff for smaller data files at least)
=> MAINT: rm extraneous to_df()

.github/workflows/linux.yml
* add [`asv check`](https://asv.readthedocs.io/en/stable/commands.html#asv-check) run to CI, which imports and checks the basic
validity of the benchmark suite without wasting a bunch of time
running it
* takes about 3 seconds to do the check locally
* commonly used in the CI of other large Python projects; i.e.,
https://github.com/scipy/scipy/blob/master/ci/azure-travis-template.yaml#L154
=> CI: add asv check to CI

darshan-util/pydarshan/benchmarks/benchmarks/dxt_heatmap.py
* add initial `asv` benchmarks for `get_heatmap_df()`, one of the
workhorse functions for the DXT heatmap handling code
* sample run: `asv run -e -b "time_get_heatmap_df"`
```
· Creating environments
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] · For pydarshan commit 0de2d06f <pydarshan-devel>:
[  0.00%] ·· Benchmarking virtualenv-py3.8-cffi-numpy-pytest
[ 50.00%] ··· Running (dxt_heatmap.GetHeatMapDf.time_get_heatmap_df--).
[100.00%] ··· dxt_heatmap.GetHeatMapDf.time_get_heatmap_df …
```
=> BENCH: benchmark get_heatmap_df()

darshan-util/pydarshan/benchmarks/benchmarks/report.py
* there's a report that in gh-397 `mod_read_all_records()`
can take up `99 %` of runtime in some cases
* draft an initial `asv` benchmark in anticipation of
potential future improvements there, etc.
* we probably want to use a much larger diversity of
log files for this, but it lays down the groundwork
=> BENCH: benchmark mod_read_all_records

darshan-util/pydarshan/darshan/backend/cffi_backend.py, darshan-util/pydarshan/darshan/report.py, darshan-util/pydarshan/tests/test_cffi_misc.py
* Performs several small changes to `log_get_generic_record`
to improve the performance of the `pandas` dataframe retrieval.
One of these optimizations is allowing the counter/fcounter
column names to be fed into the function instead of
generating them for each record.
* Add regression test `test_log_get_generic_record`
to `test_cffi_misc.py`
* Fix issue #440
=> ENH: Optimize cffi_backend.log_get_generic_record()

darshan-util/pydarshan/benchmarks/benchmarks/report.py
* add draft `asv` benchmarks for `mod_read_all_dxt_records()`
* probably needs more log file diversity to be robust, but
lays the groundwork and runs...
`asv run -b "time_mod_read_all_dxt_records"`
```
[100.00%] ··· report.ModReadAllDXTRecords.time_mod_read_all_dxt_records                                                                                                                                                                                                                                                   ok
[100.00%] ··· ======== ======================================= ================== =================== ================== ===================
--                                                                               mod / read_all …
```
=> BENCH: asv mod_read_all_dxt_records

darshan-util/pydarshan/tests/test_cffi_misc.py
* make the cleanups I requested for gh-447
* don't use `np.asarray()` when the argument cannot
possibly be an array that would get passed through
unchanged; in such cases, simply use `np.array()` since
a copy of the list data must be made regardless (and there
can be a microscopic performance benefit for small lists
on top of improved clarity of intention)
* fix the incorrect order of arguments used for
`assert_allclose()` and `assert_array_equal()`
=> MAINT: cleanups after gh-447

.github/pr_path_labeler.yml, .github/workflows/labels.yml
* for simple PR labels, leverage the github actions bot
to apply labels based on filepaths that are adjusted
* docs are here:
https://github.com/marketplace/actions/labeler
* based on example upstream:
https://github.com/scipy/scipy/pull/14677
* this is only leveraging a small subset of our
labels to begin with; can be built up later to do
more if desired
=> MAINT: use github labeler

.github/pr_path_labeler.yml
* a few more labels for the label bot
because it looks like GitHub actions treats
its own config paths separately per the bot
activity in gh-471
=> MAINT, CI: more actions labels

.github/workflows/main_ci.yml, darshan-util/configure, darshan-util/configure.in
* expand the GitHub Actions CI to include MacOS, because
we've started to discover issues with building on this
platform
* activate APMPI and APXC modules in the build, since they
will be needed for some log files in the logs repo
=> CI: add MacOS to CI

darshan-util/configure.ac
Don't use readlink, rely on autoconf `ac_abs_confdir` variable instead.
=> autoconf tweak for darshan-util macos builds

darshan-util/pydarshan/darshan/discover_darshan.py
Fixes #475
* as part of the preparation for rebasing `pydarshan-devel`
on `main`, adjust the build system to search for the new
shared object library name that is built on MacOS
* Shane and Jakob seem "ok" with this patch based on discussion
in gh-475; in the future we probably want to avoid the generic
exception catching, and maybe reduce the duplication with the
`is None` blocks, but for now just keeping it simple and following
the current structure in the `discover_darshan.py` module
=> BLD: handle MacOS dylib

.github/workflows/main_ci.yml, darshan-util/pydarshan/mypy.ini, darshan-util/pydarshan/tests/conftest.py, darshan-util/pydarshan/tests/test_report.py
Fixes #464 
Fixes #460
* provide a `pytest` fixture `log_repo_files()` that
returns a list of absolute paths for *all* files in the
`darshan_logs` package, and an empty list when this package
is absent
* add a demo test that leverages the new `log_repo_files()`
fixture, to make it easier for others to replicate this
kind of test that leverages all files in the logs repo; note
that some of the logs are large--overall test suite time jumps
from to 27.21s to 38.49s on a single core locally
* adjust CI such that it:
1) installs `importlib_resources` for testing on appropriate
Python versions
2) installs the `darshan_logs` project in some, but not all,
matrix entries, to ensure that tests can be skipped when this
package is missing
=> TST, MAINT: logs repo resources

darshan-util/pydarshan/darshan/cli/summary.py
* Replace `Any` type hint in `setup_parser()`
with `argparse.ArgumentParser`
* Fix gh-494
=> MAINT: Replace overly broad type hint

.github/workflows/main_ci.yml
* the `--enable-pydarshan` config flag is removed from
CI because this adds an extra/redundant `python setup.py install`
which could confuse attempts to install a clean wheel
build in the environment, etc.
* some related discussion in gh-476, although this doesn't
solve that apart from avoiding automatic use of `python setup.py install`
=> CI: rm --enable-pydarshan

.github/workflows/main_ci.yml
Fixes #476
* build wheels in CI instead of using the discouraged
`python setup.py install`
* not only is this the preferred way to do things these days
(because i.e., `setup.py` can have arbitrary code and the
wheel build is PEP compliant, etc.), but it also represents
how most of our end users are likely to install the package
if they use `pip`
=> CI: build wheels in CI

darshan-util/pydarshan/pyproject.toml
A small part of #507 standards adoption
* add a very simple `pyproject.toml` to move us closer
to adoption of PEP517 and PEP518
* if working properly, we should see output like this
for the `pydarshan` install in CI:
- `Building wheel for darshan (PEP 517)`
- instead of the old, less standards-compliant version:
`Building wheel for darshan (setup.py)`
* for an informal discussion of the advantages see:
https://snarky.ca/what-the-heck-is-pyproject-toml/
* I suspect some gradual cleanup of what we actually
need in `setup.py` would be needed to take real
advantage of the benefits here, but I've avoided messing
around there initially
=> BLD: add simple pyproject.toml

.github/workflows/main_ci.yml
* Add flag `--use-feature=in-tree-build` to pydarshan install
command so it installs in current directory instead of using
a temporary one. This creates the autoperf symlinks correctly.
* Remove `make add-modules` since it is unnecessary
=> CI: Update pydarshan install to install in same directory

.github/workflows/main_ci.yml, darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py, darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py
* there's a request from Kevin to support Python 3.6 for
now so add it to the CI (see: https://github.com/darshan-hpc/darshan/issues/419#issuecomment-930540108 )
* note that Python 3.6 will be EOL in just a few months:
https://devguide.python.org/#status-of-python-branches
* I suggest revisiting this in the near future, also
to keep our support surface manageable
=> CI: add Python 3.6

.github/workflows/main_ci.yml, darshan-util/pydarshan/tests/test_summary.py
* Add regression tests to cover `ReportData` methods and attributes
* Add `lxml` to list of dependencies installed in CI so html
tables can be converted to pandas dataframes
* Fix #488
=> TST: Add additional tests for summary report code

darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py, darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py
* Change heat map plotting code record loading
method from `dtype="pandas"` to `to_df()`
* Contributes to [#490](https://github.com/darshan-hpc/darshan/issues/490)
=> MAINT: Remove `dtype="pandas"` usage from DXT heat map modules

.gitignore
Maybe it depends on what version of autotools you are using as to whether these show up or not, but I'm seeing `*config.h.in~` files now.  Adding wildcard to ignore them.
=> ignore .h.in~ files too

.gitignore
backport gh-544 for `git status` sanity reasons
=> MAINT: backport ignore .h.in~ files

darshan-runtime/lib/darshan-core.c
- this value is used for wtime() offset at runtime, even if internal timing is disabled
=> calculate init_start in all cases

darshan-util/pydarshan/darshan/cli/base.html, darshan-util/pydarshan/darshan/cli/style.css, darshan-util/pydarshan/darshan/cli/summary.py
* Add `ReportFigure` to `summary.py` for collecting
figure information to simplify figure registration process
* Add infrastructure to darshan summary report
generation code that allows for adding figures
via a new method `ReportData.register_figures`
* Add entries to `style.css` to correct
formatting for figures and their captions
* Add nested loop to `base.html` to create the
figure sections and insert the encoded images
* Fix #463
=> ENH: add infrastructure for adding figures, job i/o activity section

.github/workflows/main_ci.yml
* try adding Python `3.10` to CI--I suspect it may
work for Linux but not MacOS yet, depending on GA
availability
* if that is the case, I may try to selectively activate
for Linux, but we'll see..
=> WIP, CI: add Python 3.10

darshan-util/pydarshan/benchmarks/benchmarks/report.py, darshan-util/pydarshan/tests/input/__init__.py
* Add `sample-badost.darshan` to `test_data_files_dxt` since it
contains `LUSTRE` records
* Add `sample-badost.darshan` to `time_record_collection_to_df`
benchmark so the `LUSTRE` record performance can be probed
more accurately
=> BENCH: add better log file to `time_record_collection_to_df` for `LUSTRE` performance

darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py, darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py, darshan-util/pydarshan/tests/test_heatmap_handling.py, darshan-util/pydarshan/tests/test_plot_dxt_heatmap.py
`plot_heatmap()` changes:
- Change "mods" parameter to "mod" to reflect the change to a single module key
- Change "DXT" module check to allow for any module containing "DXT"  
- Add check for input module to verify if it is in the input report
* Change "mods" parameter to "mod" for
`get_single_df_dict()` and `get_aggregate_data()`
* Update documentation for functions to reflect the parameter change
* Remove iteration over modules from
`heatmap_handling.get_single_df_dict()`
* Update documentation examples to reflect the new
data structures since aggregating data across
modules is no longer being considered
* Update `plot_heatmap()` and supporting function
call signatures to use "mod" parameter and single
key instead of list of module keys
* Correct data structures for expected
data in …
=> ENH: Add `DXT_MPIIO` support to `plot_dxt_heatmap.plot_heatmap()`

darshan-util/pydarshan/darshan/experimental/plots/__init__.py, darshan-util/pydarshan/darshan/experimental/plots/plot_io_cost.py, darshan-util/pydarshan/tests/test_plot_io_cost.py
* Add module for I/O cost figure
* Add testing module to cover I/O cost functions
* Add import to `__init__.py` to ease in importing all
plotting functions in summary report code
* Contributes to #465
=> ENH: Add I/O cost figure module and tests

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/tests/test_summary.py
* Adjust `DXT_POSIX` heat map figure registration to incorporate
`DXT_MPIIO` such that either/both will be plotted when present
* Change logic such that DXT help message will only
be displayed if no DXT modules are present
* Fixes issue #538
=> ENH: Add `DXT_MPIIO` heat map to Darshan Summary Report

darshan-util/pydarshan/darshan/report.py, darshan-util/pydarshan/tests/test_report.py
This might provide some more desirable behavior when working with many logs in a single process such as raised by #578.
This pull requests adds hooks for `__del__`, `__enter__`,`__exit__` to call a cleanup routine to ensure opened log files are also closed when the object is destroyed.
=> Ensure files are closed when destructing report objects.

darshan-util/pydarshan/darshan/experimental/plots/plot_io_cost.py, darshan-util/pydarshan/tests/test_plot_io_cost.py
* Change `plot_io_cost()` to iterate over all supported modules
and plot them in a single figure
* Correct `plot_io_cost()` call signatures and expected data
for `test_plot_io_cost.py` tests `test_get_io_cost_df`,
`test_plot_io_cost_ylims`, and `test_plot_io_cost_y_ticks_and_labels`
* Replace `by-average` x-axis label with module names
* Fixes #574
=> MAINT: Plot multiple modules in single IO cost plot

darshan-util/pydarshan/darshan/experimental/plots/plot_io_cost.py, darshan-util/pydarshan/tests/test_plot_io_cost.py
* Update y-axis ticks for I/O cost figure to have a maximum
value of the runtime calculated from the log metadata
* Correct and add new cases for test `test_plot_io_cost_ylims`
to regression guard against future y limit changes
* Correct test `test_plot_io_cost_y_ticks_and_labels`
* Fixes #591
=> BUG: Correct I/O cost figure y limits

darshan-util/pydarshan/darshan/experimental/plots/plot_access_histogram.py
* Move `autolabel` function outside of `plot_access_histogram`
to allow for easier testing
* Add `ax` parameter to `autolabel` and correct call signatures
* Contributes to issue #577
=> MAINT: Move `autolabel` function out of `plot_access_histogram`

darshan-util/pydarshan/darshan/experimental/plots/plot_io_cost.py, darshan-util/pydarshan/tests/test_plot_io_cost.py
* Correct the calculation in `plot_io_cost.get_by_avg_series()`
to remove the division by number of records
* Remove "ranks" column attachment and downstream
code since it is no longer necessary
* Fix tests `test_get_io_cost_df` and `test_get_by_avg_series`
to reflect changes in I/O cost calculations
* Close #590
=> BUG: Fix `plot_io_cost()` calculation

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/experimental/plots/plot_io_cost.py, darshan-util/pydarshan/tests/test_summary.py
* Add I/O cost figure into new report
section "Cross-Module Comparisons"
* Add `plt.close()` to `plot_io_cost()`
so figures are properly closed
* Add checks to tests `test_summary.test_main_without_args()`
and `test_summary.test_main_all_logs_repo_files()` to ensure
I/O cost figures are being generated when the relevant modules
are present in the report
* Add check to `test_summary.test_main_without_args()` which
counts the number of `img` tags in the HTML report to regression
guard the figure counts in the reports
* Contributes to #465
=> WIP, ENH: Add I/O cost figure to Darshan Summary Report

darshan-util/pydarshan/darshan/experimental/plots/plot_opcounts.py, darshan-util/pydarshan/tests/test_plot_exp_common.py
* Modify `plot_opcounts` to plot a single module
* Merge `MPIIO` collective and independent operations and update
the label names to better reflect the operations being used
* Remove unused `STDIO` "stat" and "mmap"
operations and change `Fsync` to `Flush`
* Correct bar annotation x-coordinate to
use bar midpoint in `autolabel`
* Remove the figure legend as there are no longer bar labels
* Correct tests in `test_plot_exp_common.py`:
- Refactor parametrizations in `test_xticks_and_labels` to allow
for plotting function and module specific x-axis tick labels
- Fix `plot_opcounts` test cases in `test_bar_heights` by
providing the module names and splitting up the original
`expected_heights` arrays for their respective modules
* Addresses first 2 tasks in issue #569
=> MAINT: Single module `plot_opcounts`

darshan-runtime/configure.ac, darshan-runtime/lib/darshan-core.c
- also remove unused (deprecated) DARSHAN_CORE_LOCK() macros that have
been replaced with __DARSHAN_CORE_LOCK() in the code
Fixes #604
=> add missing stdatomic autoconf test

darshan-util/pydarshan/tests/test_log_utils.py
* add some basic regression tests for `get_log_path()`;
focuses on the usage in the `pytest` context, which is
the main use case
* no noticeable test suite slowdown measured locally with logs repo
present
=> TST: tests for get_log_path()

darshan-util/pydarshan/benchmarks/benchmarks/log_utils.py
Related to some concerns in gh-606.
* add a benchmark for repeated calls to `get_log_path()`,
which is a situation likely to arise in the context of the
full `pytest` suite where many log files are retrieved
* benchmark runs in 42 seconds locally:
`time asv run -e -b "time_get_log_path_repeat"`
```
· Creating environments
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] · For pydarshan commit 6d0a48e0 <pydarshan-devel>:
[  0.00%] ·· Benchmarking virtualenv-py3.9-cffi-numpy-pytest
[ 50.00%] ··· Running (log_utils.GetLogPath.time_get_log_path_repeat--).
[100.00%] ··· log_utils.GetLogPath.time_get_log_path_repeat
ok
[100.00%] ··· =========== =============
--             filename
----------- -------------
num_calls   dxt.darshan …
```
=> BENCH: asv benchmark for get_log_path()

darshan-util/pydarshan/benchmarks/benchmarks/dxt_heatmap.py
Fixes #586 
* fix the call signature of `plot_heatmap()` in
`time_plot_heatmap_builtin_logs()` so that the
benchmark no longer fails
* locally, ` asv run -e -b "time_plot_heatmap_builtin_logs"`:
```
· Creating environments
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] · For pydarshan commit 6d0a48e0 <pydarshan-devel>:
[  0.00%] ·· Benchmarking virtualenv-py3.9-cffi-numpy-pytest
[ 50.00%] ··· Running (dxt_heatmap.PlotDXTHeatMapSmall.time_plot_heatmap_builtin_logs--).
[100.00%] ··· dxt_heatmap.PlotDXTHeatMapSmall.time_plot_heatmap_builtin_logs …
```
=> BUG, BENCH: fix time_plot_heatmap_builtin_logs

darshan-util/pydarshan/darshan/log_utils.py
Related to gh-606.
* this is a precursor to using `get_log_path()` ubiquitously
in the test suite, which itself is a precursor to being
able to run the test suite from any directory (including
a user/developer with a `spack` install of `py-darshan`, which
is our primary planned vehicle for initial delivery of the new
report capability)
* achieve nearly constant-time log filepath retrieval
using a dictionary/hash table
* the speedups on repeated calls, the most important scenario
for running in `pytest`, are several orders of magnitude faster using
the new benchmark in gh-610:
`asv continuous pydarshan-devel treddy_get_log_path_dict -e -b
"time_get_log_path_repeat`
```
before           after         ratio
[6d0a48e0]       [47e9a462]
<pydarshan-devel>       <treddy_get_log_path_dict>
- …
```
=> ENH: faster get_log_path()

darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py, darshan-util/pydarshan/pytest.ini
* Fixes issue when running tests where many figures are opened and
not explicitly closed, generating a pytest warning
* Add `pytest.ini` to upgrade `matplotlib`-generated
RuntimeWarnings into errors
=> MAINT: Close dxt heatmap matplotlib figures, add `pytest.ini`

ChangeLog, darshan-runtime/configure.ac, darshan-runtime/lib/Makefile.am, darshan-runtime/lib/darshan-heatmap.c, darshan-runtime/lib/darshan-heatmap.h, darshan-runtime/lib/darshan-mpiio.c, darshan-runtime/lib/darshan-posix.c, darshan-runtime/lib/darshan-stdio.c, darshan-runtime/lib/darshan.h, darshan-util/Makefile.am, darshan-util/darshan-heatmap-logutils.c, darshan-util/darshan-heatmap-logutils.h, darshan-util/darshan-logutils.h, darshan-util/doc/darshan-util.txt, include/darshan-heatmap-log-format.h, include/darshan-log-format.h
This PR introduces an auto-scaling heatmap histogram at runtime; see darshan-heatmap.c.
Multiple APIs can register with it and keep independent histograms (each histogram is a separate Darshan record).  All of the histogram records are stored in a single dedicated histogram module from a log perspective.
PR currently just has the runtime library portion implemented, and it is only hooked up to the POSIX module.  Need to:
=> runtime heatmap generation

darshan-util/darshan-logutils.c, darshan-util/darshan-logutils.h
This is a minor cleanup for clarity.  No bzip symbols are needed in public API, and ifdef guard likely doesn't work once header is installed.  This is only needed in the .c file.
=> move bzip header include to .c file

darshan-util/pydarshan/darshan/cli/base.html, darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/experimental/plots/plot_common_access_table.py, darshan-util/pydarshan/darshan/tests/test_plot_common_access_table.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* Update method `generate_img` name to more general `generate_fig`
and update documentation to reflect the changes
* Generalize `generate_fig` to support figure
functions that generate pandas dataframes
* Add test `test_generate_fig_unsupported_fig_type` to
check appropriate error is raised when input function
does not generate the supported figure types
* Add object `DarshanReportTable` to `plot_common_access_table.py`
for storing tables in dataframe and html format. Should set a
standard that allows access for testing but also puts the burden
on the figure function to generate a `DarshanReportTable` that
contains the desired html table for the report.
* Change `plot_common_access_table` to return
`DarshanReportTable` and update documentation
* Fix `test_common_access_table` due to above …
=> ENH: Add dataframe/table figure support

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* Add "Per-Module Stats" section to report
containing the common access size table (to start)
* Extend `test_main_without_args` to check for number of tables
generated as a regression guard
=> ENH: Add common access size table to darshan summary report

darshan-util/pydarshan/darshan/cli/base.html, darshan-util/pydarshan/darshan/tests/test_summary.py
* Relocate section closing tag to outside of figure loop
* Add check to tests `test_main_without_args` and `test_main_all_logs_repo_files` to verify the number of close/open section tags match
=> BUG: correct section closing tag in `base.html`

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* Add access size histogram figure from
`plot_access_histogram` to summary report
* Update expected `img` tag counts in `test_main_without_args`
to account for new access size histogram figures
* Rework table counting in `test_main_without_args` to ignore
extraneous instances of the word "table", such as the instance
in the figure caption for the access size histogram
* Contributes to issue #465
=> ENH: Add access size histogram to summary report

darshan-util/pydarshan/darshan/tests/test_log_utils.py, darshan-util/pydarshan/darshan/tests/test_plot_common_access_table.py, darshan-util/pydarshan/darshan/tests/test_plot_io_cost.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* Correct all instances of `nonmpi_partial_modules.darshan` to
`nonmpi_dxt_anonymized.darshan` after the following darshan-logs
PR was merged:
https://github.com/darshan-hpc/darshan-logs/pull/19
=> MAINT: Correct `nonmpi_partial_modules.darshan` filename

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/experimental/aggregators/mod_agg_iohist.py, darshan-util/pydarshan/darshan/tests/test_plot_exp_common.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* Add `H5D` to supported module list for `mod_agg_iohist`
* Add `H5D` access histogram to summary report
* Add test cases for `ior_hdf5_example.darshan`:
- `test_main_without_args()` in `test_summary.py`
- `test_xticks_and_labels()` and `test_bar_heights()`
in `test_plot_exp_common.py`
* Fix issue #639
=> ENH: Add `H5D` module support to "Access Size Histogram"

darshan-util/pydarshan/benchmarks/benchmarks/dxt_heatmap.py, darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py, darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py, darshan-util/pydarshan/darshan/tests/test_heatmap_handling.py, darshan-util/pydarshan/darshan/tests/test_plot_dxt_heatmap.py
* Use `nprocs` to scale y-axis for heatmap figure
instead of number of ranks with IO activity
* Add `nprocs` parameter to `get_heatmap_df`
and update documentation
* Update `get_heatmap_df` to return dense dataframe based on `nprocs`
* Correct tests in `test_plot_dxt_heatmap.py` for cases 
where not all ranks had non-zero bins
* Correct tests in `test_heatmap_handling.py` to reflect
dense heatmap dataframe output
* Fixes issue #576
* Contributes to issue #575
=> BUG: Change DXT heatmap to use `nprocs` for y-axis scale and correct bar graph anomalies

darshan-runtime/lib/darshan-common.c, darshan-runtime/lib/darshan-core.c, darshan-runtime/lib/darshan-posix.c, darshan-runtime/lib/darshan.h, darshan-util/darshan-convert.c, darshan-util/darshan-logutils.c
Use internal __DARSHAN_PATH_MAX define instead.   Also add additional buffer length safety checks and comments to existing checks.
Fixes #623
=> eliminate use of PATH_MAX constant

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* Change method `ReportData.get_runtime()`
to use integers instead of floats
* Correct tests `test_metadata_table` and
`test_get_runtime` to use integer values
* Fixes task "Change runtime data type to integer" in gh-641
=> MAINT: Update darshan summary report metadata table runtime datatype

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* Change partial flag message to "Module data incomplete
due to runtime memory or record count limits"
* Correct test `test_module_table` to reflect
updated partial data flag message
* Fixes task "Update partial flag message" in gh-641
=> MAINT: Update partial flag message

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* Move "Log Filename", "Runtime Library Version", and
"Log Format Version" metadata into "Darshan Log Information"
section of summary report
* Correct tests `test_metadata_table` and `test_module_table`
to reflect new organization of log metadata
* Close issue #641
=> MAINT: Reorganize summary report metadata sections

darshan-util/pydarshan/darshan/log_utils.py, darshan-util/pydarshan/darshan/tests/conftest.py, darshan-util/pydarshan/darshan/tests/test_report.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* only test cases that require runtime `HEATMAP`
module support are `xfail`ed in the test suite now,
instead of skipping the cases that also come after
them in iterable tests
* while the original design was meant to be temporary (gh-671),
and was made intentionally on the assumption that HEATMAP
support would be added shortly, this introduces parametrization
into the two tests that are involved and does away with the
old fixtures to avoid debates like the one in https://github.com/darshan-hpc/darshan-logs/pull/27
* on `pydarshan-devel`:
`300 passed, 2 xfailed in 38.83s`
* on this branch:
`318 passed, 6 xfailed in 96.56s (0:01:36)`
* there are 3 runtime heatmap logs, and two tests that
need to avoid them, so the xfail arithmetic looks correct there,
along with the restoration of a bunch …
=> TST: graceful HEATMAP xfails

ChangeLog, darshan-util/darshan-convert.c, darshan-util/darshan-diff.c, darshan-util/darshan-dxt-parser.c, darshan-util/darshan-merge.c, darshan-util/darshan-parser.c, include/darshan-log-format.h
- bug reported by Jakob Luettgau
- prevents memory corruption when attempting to parse logs that have compatible log format but contain unknown log ids
Fixes #621
=> gracefully parse logs with unknown module ids

darshan-util/pydarshan/darshan/tests/test_report.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* ~we no longer need to mark runtime `HEATMAP` tests
as known failures, since the binding support has been
merged now~
* narrow the `HEATMAP` xfail to only exclude `e3sm_io_heatmap_and_dxt.darshan`, which still uses too much memory
=> TST:  narrow heatmap xfail

darshan-util/pydarshan/darshan/experimental/aggregators/agg_ioops.py, darshan-util/pydarshan/darshan/experimental/plots/plot_opcounts.py, darshan-util/pydarshan/darshan/tests/test_plot_exp_common.py
Description
------------
* Adds `H5F` and `H5D` specific sections to `plot_opcounts()`
aggregator functions `agg_ioops()` and `gather_count_data()`.
Current method does not combine `H5F` and `H5D` module
data together.
* Add `H5F` and `H5D` test cases to `test_plot_exp_common`
tests `test_xticks_and_labels` and `test_bar_heights`
* Contributes to issue #663
Considerations
----------------
I've played around with combining the `H5F` and `H5D` module data, and we can combine them fairly easily in `gather_count_data()` if we want to. The following diff shows one way of accomplishing this on this branch:
<details><summary>Diff</summary>
```diff
diff --git a/darshan-util/pydarshan/darshan/experimental/plots/plot_opcounts.py b/darshan-util/pydarshan/darshan/experimental/plots/plot_opcounts.py …
```
=> WIP, ENH: HDF5 support for `plot_opcounts()` aggregators

darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py, darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py, darshan-util/pydarshan/darshan/tests/test_plot_dxt_heatmap.py
* Update `plot_heatmap()` to use the runtime for scaling x-axis
* Add `tmax` parameter to `get_heatmap_df` to allow for setting
the heatmap maximum time. Default behavior is to use the final
DXT segment end time.
* Add logic to `plot_heatmap` to prevent truncation of data
when using the job runtime for setting plotting boundaries
* Change `set_x_axis_ticks_and_labels()` and
`get_x_axis_tick_labels()` to use runtime for
x-axis labels
* Update `set_x_axis_ticks_and_labels()` parameters and expected
xticklabels in `test_set_x_axis_ticks_and_labels()`
* Contributes to x-axis rescaling portion of issue https://github.com/darshan-hpc/darshan/issues/575
This gets us closer to resolving gh-652 because it removes the dependence on `get_aggregate_data()`, at least when it comes to the x-axis …
=> MAINT: Use runtime for DXT heatmap x-axis scaling

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* Add `H5D` or `H5F` to operation count figure modules.
Only 1 module is added since `H5D` figure encompasses
both HDF5 modules' data.
* Correct expected figure count in `test_main_without_args`
for `ior_hdf5_example.darshan` case since `H5D` section
now contains an operation counts figure.
* Contribute to issue #663
=> ENH: Add HDF5 operation counts figures to summary report

darshan-util/pydarshan/darshan/tests/test_plot_exp_common.py
* Add appropriate close statement to ensure each figure
in `test_plot_exp_common.test_bar_heights` is closed.
* Fix issue darshan-hpc/darshan-logs#34
* Both CI commands pass after this change:
- `pytest --pyargs darshan`
- `pytest --import-mode=importlib`
=> TST: Close figures in `test_bar_heights`

.github/workflows/main_ci.yml
* [follow NumPy](https://github.com/numpy/numpy/pull/21307) in bumping to latest versions
of the actions
=> CI: bump GHA action versions

darshan-util/pydarshan/darshan/cli/summary.py
* Change the per-module report section titles to
`Per-Module Statistics: HDF5` for `H5F` and `H5D` figures
* Fix issue #663
=> MAINT: Change `H5D` and `H5F` figure section titles to HDF5

darshan-util/pydarshan/darshan/experimental/plots/plot_opcounts.py, darshan-util/pydarshan/darshan/tests/test_plot_exp_common.py
Description
--------------
* Change operation counts figure to always list columns for
both `H5F` and `H5D` modules. When `H5D` module data is not
present the values are set to zero.
* Contribute to issue #706
Example
----------
Here is the updated operation counts figure for `hdf5_file_opens_only.darshan`:
=> MAINT: Include `H5D` columns in `H5F`-only operation counts figure

darshan-util/pydarshan/darshan/tests/test_plot_common_access_table.py, darshan-util/pydarshan/darshan/tests/test_plot_exp_common.py
Description
-------------
* Add "ground truth" testing log cases to `test_common_access_table`
and change the number of rows to be configurable based on the
number of rows in the input `expected_df`
* Add "ground truth" testing log cases to `test_plot_exp_common.py`
tests `test_xticks_and_labels` and `test_bar_heights` to check
results for `plot_opcounts` and `plot_access_histogram`
* Fix issue https://github.com/darshan-hpc/darshan/issues/706
Considerations
-----------------
This branch is based off of the feature branch in gh-711, so it should be reviewed/merged last.
=> TST: Add HDF5 test cases using "ground truth" logs 

darshan-util/pydarshan/darshan/datatypes/heatmap.py, darshan-util/pydarshan/darshan/tests/test_report.py
* Add multiple operation (i.e. read and write) data aggregation
in `Heatmap.to_df()` method. This more closely reflects the way
other heatmap-related functions operate which should allow for 
a more seamless integration of the runtime heatmap into 
`plot_heatmap()`.
* Correct call signatures for heatmap `to_df()` method
* Add test `test_heatmap_operations` for checking different
operation inputs and comparing their results
* Fix issue #697
=> ENH: Runtime heatmap multiple operation support

darshan-util/pydarshan/Makefile, darshan-util/pydarshan/devel/build-wheels.sh
This pull request changes the wheel building procedure by not installing pydarshan dependencies to the manylinux docker container with the following effects:
* This aviods running into build error because of dependencies changing their build procedure (an alternative could be to pin to a working set of dependencies)
* The build is significantly faster as various dependencies would attempt to build from source
* But, we can not run tests directly after building (but we did not do this so far anyways)
I also made two small changes to the Makefile:
* `make wheels` now automatically issues add-modules
* the add-modules target performs `git submodule init `and `git submoudle update`
=> PyDarshan: Mitigate build errors from dependencies and speedup wheel building

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/experimental/plots/data_access_by_filesystem.py, darshan-util/pydarshan/darshan/tests/test_data_access_by_filesystem.py, darshan-util/pydarshan/darshan/tests/test_summary.py
Fixes #466 (eventually)
* add the "Data Access by Category" figure to the Python
summary report, and adjust tests to reflect the additional
figure, and support for both `POSIX` and `STDIO` with this fig
* some issues to think about
- ~the new figure is ridicuously large compared to the previous
figures in the report and the option to specify the width
of the figure in the `ReportFigure` has no effect--see example in gh-717~
- if we have a sample log that lacks both `POSIX` and `STDIO`,
then `test_posix_absent` might be suitably replaced instead
of deleted (may help if test coverage isn't 100 % anymore)
- the code changes here contain comments about an eventual API redesign,
the issue there should hopefully be clear from the diff
- test suite ran in 3:34 on 6 cores locally--didn't quantify …
=> WIP, ENH: summary with data access cats

.github/workflows/main_ci.yml, darshan-util/pydarshan/darshan/experimental/plots/data_access_by_filesystem.py, darshan-util/pydarshan/darshan/tests/test_data_access_by_filesystem.py
Fixes #678
* only allow `POSIX` and `STDIO` records
to get passed through the control flow
that produces the "Data Access by Category"
plots
* add one new test case and adjust old cases
to reflect the more selective plotting of
categories
Below the fold I'll place the updated examples for the problematic cases
cited in the matching issue. It is trivial to add new test cases so if reviewers
have others they know pretty well and want to see tested that should be easy
enough to do.
<details>
<summary>
For mpi-io-test that had spurious autoperf entries and inactive std streams
</summary>
</details>
<details>
<summary>
For the Tensorflow monitoring log that had spurious heatmap entries and inactive std streams
</summary>
</details>
I have to admit that because this makes the number of …
=> BUG: cats only allow POSIX/STDIO

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py, darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py, darshan-util/pydarshan/darshan/tests/test_plot_dxt_heatmap.py, darshan-util/pydarshan/darshan/tests/test_summary.py
Fixes #652
* add the runtime (`HEATMAP` module) heatmaps to
the pydarshan/Python summary reports
* adjust some tests to reflect the new runtime `HEATMAP`
support and to test some components of it in a bit
more detail
* design considerations:
- at the moment, the runtime heatmaps are placed first, but it may
be helpful to grid i.e., POSIX versions of DXT and runtime maps
side-by-side to make the comparisons less jarring
- it is a bit awkward that `DXT` data is directly associated with the
module data source like `DXT_POSIX`, while for `HEATMAP` we index
into a "submodule" dictionary--this awkwardness should be clear in
the diff--not sure if we want to do anything about that
- the new `determine_hmap_runtime()` function was added to provide
a common abstraction when plotting heatmap data …
=> ENH: summary with runtime heatmaps

darshan-util/pydarshan/darshan/cli/base.html, darshan-util/pydarshan/darshan/cli/style.css, darshan-util/pydarshan/darshan/tests/test_summary.py
Description
-------------
* Use stylesheet from the following location:
https://unpkg.com/style.css@1.0.0/style.css
* Misc adjustments to stylesheet:
- Add margins to body so titles and figures
do not touch window edge
- Remove `figure` border
- Add `td:empty` entry to prevent empty columns in
"Darshan Log Information" table from being displayed
- Change horizontal rule height to 1px, make color darker
- Remove table tr `border-top`
- Change table pattern to `2n+1` so tables
start with darker color
* Correct expected string in `test_stylesheet`
* Add CSS class `section_header`, add to section
title tags to more clearly delineate sections
* Remove "Gill Sans" font family from body
Comments
------------
There has been a fair amount of discussion about adding a proper CSS style sheet to the …
=> WIP, ENH: Update summary report styling

.github/workflows/build_wheels.yml, darshan-util/pydarshan/RELEASE-CHECKLIST-PyDarshan.txt, darshan-util/pydarshan/devel/build-wheels.sh, darshan-util/pydarshan/pyproject.toml, darshan-util/pydarshan/setup.py
This PR includes updates for supporting `cibuildwheel`:
- `cibuildwheel` configuration in `pyproject.toml` which works for my local Linux builds over Docker
- first cut at GitHub workflow for automatically building wheels on updates to code that affects PyDarshan
- change `setup.py` argument `--with-extension` to env variable `PYDARSHAN_BUILD_EXT` 
The last change was needed because I couldn't find any other way to get user arguments to `setup.py` from `cibuildwheel`. There seems to be lack of general support in `cibuildwheel` for user-specified options to `setup.py`, as well as issues with `pip` supporting the `--build-option` flag we had been using -- see discussion at https://github.com/pypa/cibuildwheel/issues/268. The issue with `--build-option` is what I think was leading to …
=> MAINT, CI: cibuildwheel support

.github/workflows/main_ci.yml, darshan-util/pydarshan/darshan/experimental/plots/data_access_by_filesystem.py
* treat all `FutureWarning` as errors in the `pytest`
CI checks, and fixup the large number of `FutureWarning`s
coming from usage of `df.append()` by using the more modern
`pd.concat()` instead
* the full testsuite drops from 819 to 48 warnings for me
locally, as a result of this change
=> MAINT: deal with pd deprecation

darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py, darshan-util/pydarshan/darshan/tests/test_summary.py
* deal with 1/2 of the issue described in gh-730
* allow `plot_heatmap()` to gracefully handle
the scenario where a log file has some inactive
ranks and the new runtime `HEATMAP` tracking
* this branch is meant to accompany the new logs
repo PR: https://github.com/darshan-hpc/darshan-logs/pull/37
* minor testing changes to accomodate that new
log file; the test suite will fail with that new
log file without the patch provided here
If you're curious, this is what the new HEATMAP looks like for that log file we couldn't previously process, with the "darker" ranks printing one extra character because the `printf` includes i.e., `rank 10` instead of `rank 9` (so the heatmap scale is super sensitive here).
=> BUG: pydarshan HEATMAP inactive handle

darshan-runtime/lib/darshan-config.c
As mentioned in #743, Darshan seg faults on any attempts to set `DARSHAN_MOD_DISABLE`/`DARSHAN_MOD_ENABLE` env vars.
This was a simple fix, I had not properly accounted for some variable name changes I made right before merging this in.
Fixes #743
=> fix segfault affecting DARSHAN_MOD_DISABLE/ENABLE env vars

darshan-util/darshan-job-summary/bin/darshan-job-summary.pl.in
- only extract counter info for POSIX, MPI-IO, and STDIO modules
- chop off some extra ("# MiB/s") from performance estimates
Fixes #759
=> tweaks to darshan-job-summary.pl to suppress noisy output

darshan-runtime/configure.ac, darshan-runtime/doc/darshan-runtime.txt, darshan-runtime/lib/darshan-core.c
PR contains the following:
- updates to `darshan-runtime` autoconf and core code to make `cuserid()` usage opt-in
- corresponding changes/simplifications to docs
Fixes #699
=> make `cuserid()` usage opt-in

darshan-runtime/lib/darshan-mpiio.c
As discussed in #698, we should be careful in Darshan not to call `MPI_Type_size()` when applications are using `MPI_DATATYPE_NULL` type.
This PR adds a couple of checks to the two locations in the MPI-IO module where we use this call, to make sure we don't call if the app uses a zero value for `count` or if the app is using `MPI_DATATYPE_NULL`.
There is a similar PR open on the AutoPerf repo which fixes a similar issue in the APMPI module, which was the ultimate source of the reported bug: https://github.com/argonne-lcf/autoperf/pull/15
=> don't call `MPI_Type_size()` on `MPI_DATATYPE_NULL` in MPI-IO module

darshan-util/darshan-logutils.c, darshan-util/darshan-logutils.h
PyDarshan makes use of a `darshan_log_get_filtered_namehash()` routine that does not have proper handling in place to account for some log format changes that affected name records from 3.00 to 3.01 format version. This causes darshan-util library to abort on affected log format versions (3.00), as follows:
```
[chiusole@cori09:cori]$ python
Python 3.9.12 (main, Jun  1 2022, 11:38:51)
>>> import darshan
>>> report = darshan.DarshanReport("/global/cscratch1/sd/chiusole/logfile_causing_assertion_error.darshan")
python: darshan-logutils.c:714: darshan_log_get_filtered_namehash: Assertion `buf_len == 0' failed.
Aborted
```
I refactored all of the namehash/namerec routines to share as much code as possible, and to ensure the routine mentioned above properly handles backwards compatibility. …
=> bug fix + refactoring of `log_get_namerec` routines

.github/workflows/runtime_ci.yml, .gitignore, darshan-test/python_mpi_scripts/runtime_prog_issue_690.py, darshan-test/python_runtime_tests.py
* this adds end-to-end functional CI testing from
the darshan runtime monitoring MPI IO activity
right through to the Python bindings checking
for the expected result; you can run this locally (containerized)
with the `act` tool with i.e.,
`act -j test_runtime`
* when cherry-picked into gh-751, this reproduces
the exact error I was hoping CI could catch as
described here:
https://github.com/darshan-hpc/darshan/pull/751#issuecomment-1150197393
* otherwise, running this locally produces the expected failure
to capture `H5D` events when reading with `h5py`, with
only the write, but not the read event going through
the expected API path until Shane's PR (gh-751) is
ready
```
| >           assert h5d_df_counters["H5D_OPENS"].to_numpy() == n_ranks * 2
| E           assert array([1]) == (1 * 2) …
```
=> CI, TST: early draft of functional testing

darshan-util/pydarshan/pyproject.toml
Fixes #744
* install the darshan logs project prior to running
the `cibuildwheel` testsuite so that the release
manager can be more confident in the quality
of wheels prior to future releases
* we thought this was blocked on making a PyPI
package for the logs repo, but it is not because
we can just use `pip` to install manually from the
GitHub address as done here
* since the tests currently run on a single core
for these CI jobs, it will likely add 5-6 minutes
per wheel build to the CI time, but I think this is
worth it if it helps avoid a premature release for
the release manager
* a single-wheel spot check locally shows the extra
tests running on this branch vs. latest `main`:
`CIBW_BUILD="cp39-*" cibuildwheel --platform linux darshan-util/pydarshan`
```
414 passed, 2 xfailed, 12 …
```
=> MAINT, CI: logs repo for cibuildwheel

darshan-runtime/configure.ac, darshan-runtime/lib/darshan-hdf5.c, darshan-runtime/share/ld-opts/darshan-hdf5-ld-opts.in
This PR contains a few changes to the runtime component of our HDF5 module:
* autoconf changes to conditionally compile in support for various functions (e.g., `H5Dflush`, `H5Sget_regular_hyperslab`) based on `AC_CHECK_FUNCS` checks rather than checking the HDF5 version number
* don't attribute read/write accesses to entire HDF5 datasets (i.e., 'ALL' selections) to `H5D_REGULAR_HYPERSLAB_SELECTS` counter -- there is no `ALL` variant of Darshan counters, but it can be deduced from current counters (total number of reads/writes minus total point/regular-hyperslab/irregular-hyperslab counts)
* compiler warning fixes for HDF5 versions greater than or equal to 1.8 and less than 1.10
=> HDF5 autoconf changes + hyperslab instrumentation fixes

darshan-runtime/configure.ac, darshan-runtime/lib/darshan-hdf5.c, darshan-runtime/share/ld-opts/darshan-hdf5-ld-opts.in
It's possible for HDF5 users to open datasets using a more generic `H5Oopen` call (see discussion linked in #690), which is the case for h5py read path, for instance.
Since Darshan does not intercept `H5Oopen`, it does not store any state about the open dataset, causing subsequent dataset read/write calls to bail out, since they do not know which open dataset to attribute the I/O activity to.
This PR adds new wrappers for `H5Oopen`/`H5Oclose` to support instrumentation of datasets accessed in this manner. Code is nearly identical to `H5Dopen`/`H5Dclose`, sans an additional check here to only store state on opened dataset objects.
=> Add support for H5Oopen

darshan-util/pydarshan/darshan/experimental/plots/plot_opcounts.py, darshan-util/pydarshan/darshan/tests/test_plot_exp_common.py, darshan-util/pydarshan/darshan/tests/test_summary.py
Fixes #709
* the new Python summary report can now gracefully
handle the case where `H5F` is intentionally disabled
via the new mechanism provided in gh-703
* add a new test using the log file from
https://github.com/darshan-hpc/darshan-logs/pull/38
* minor testing adjustments to account for the extra
log file in suite
* using zeros instead of "N/A" type fillers is convenient
here, but we could always decide to change that later if
the absence of the module from the module list above in the
report is not clear enough
Here's the `HDF5` section of the new summary report for this log,
which should reflect the 3 ranks writing 5 H5D bytes each (the log
would error out with current `main`):
=> ENH: handle H5F absence

darshan-runtime/lib/darshan-config.c, darshan-runtime/lib/darshan-config.h, darshan-runtime/lib/darshan-core.c, darshan-runtime/lib/darshan.h, darshan-util/darshan-dxt-parser.c, darshan-util/darshan-logutils.c, darshan-util/darshan-logutils.h, include/darshan-log-format.h
This PR bumps Darshan's MAX_MODS value from 16 to 64. This is a small change to the header for the most part.
There are additional commits to address a couple of other issues:
- switched almost all references to `DARSHAN_MAX_MODS` to `DARSHAN_KNOWN_MODULE_COUNT` for safety purposes (fixes #712)
- small `darshan-dxt-parser` fix to align behavior with `darshan-parser` -- make sure to include info in the module summary section of parser output for modules that report partial data
This PR is marked WIP for a few reasons:
1. There is no backwards-compatibility support currently for previous log versions. I am still working on that.
2. No Python bindings support for this change yet.
3. I don't want to rush this in ahead of the upcoming pre-release, we can make sure we get this right and get it …
=> increase MAX_MODS to 64

ChangeLog, darshan-util/darshan-parser.c, darshan-util/darshan-summary-per-file.sh, darshan-util/doc/darshan-util.txt
See discussion in #677 and possible long-term solution in #781 .  The --file-list and --file-list-detailed options are not frequently used (especially given other options available for analysis now), but their presence was making it difficult to refactor parser to use accumulator API because the --file-list features requires the parser to construct it's own explicit hash table of file records.
It would make more sense to maintain a more generalized version of this functionality elsewhere and reduce complexity in darshan-parser for now.
Fixes #782 .
=> Remove  --file-list and --file-list-detailed options from darshan-parser

darshan-runtime/configure.ac
The autoconf logic that allows for autodiscovery of HDF5 prefixes using the location of `h5dump` binary is broken, at least on Cray systems. It looks like the organization of Cray software module install directories has changed slightly (as shown below), with us not being able to find a `lib` folder at the same directory level of the `bin` folder containing `h5dump`:
```
snyder@thetalogin4:~/software/darshan/darshan-dev/build> which h5dump
/opt/cray/pe/hdf5-parallel/1.10.6.1/bin/h5dump
snyder@thetalogin4:~/software/darshan/darshan-dev/build> ls /opt/cray/pe/hdf5-parallel/1.10.6.1/
bin  COPYING  crayclang  CRAYCLANG  gnu  GNU  include  intel  INTEL  set_pkgconfig_default_hdf5-parallel  share
```
Ultimately, this issue results in autoconf silently using a bad `lib` path for HDF5 which is …
=> [BUG] darshan-runtime: small fix to HDF5 autodetect autoconf logic

ChangeLog, darshan-util/Makefile.am, darshan-util/configure.ac, darshan-util/darshan-logutils-accumulator.c, darshan-util/darshan-logutils.h, darshan-util/darshan-mpiio-logutils.c, darshan-util/darshan-parser.c, darshan-util/darshan-posix-logutils.c, darshan-util/darshan-stdio-logutils.c, darshan-util/tests/unit-tests/Makefile.subdir, darshan-util/tests/unit-tests/README.md, darshan-util/tests/unit-tests/darshan-accumulator.c, darshan-util/tests/unit-tests/munit/LICENSE, darshan-util/tests/unit-tests/munit/munit.c, darshan-util/tests/unit-tests/munit/munit.h
- Adds a "darshan_accumulator" API to the logutils library
- _create(), _inject(), _emit(), and _destroy()
- generalizes the mechanism for producing summation records and derived metrics for sets of records from a given module
- refactors darshan-parser to use new API
- implements support for accumulators in POSIX, STDIO, and MPIIO modules
* Integrates the µnit Testing Framework in darshan-util
- implements unit tests for darshan_accumlator API; they can be invoked with `make check` at the top level build directory
Note that this does not include Python bindings; those need to be added separately after this is merged so that these routines can be used withing Python utilities.
Fixes #642
=> logutils accumulator API

darshan-runtime/doc/darshan-runtime.txt, darshan-util/doc/darshan-util.txt
darshan-runtime and darshan-util docs needed to be updated to reflect the move of `prepare.sh` script to the top-level of the repo.
=> DOC: update docs to reflect new location of prepare.sh

darshan-util/darshan-logutils.c
The logutils library is not properly up-converting the module partial flags contained in the header to account for the H5D module placed after the original HDF5 file module in version 3.2.0. This means that logs prior to 3.2.0 that are parsed by newer versions of Darshan will have an "off-by-1" bug in terms of module partial flags, with this bug affecting all modules following HDF5 in Darshan's module list.
This PR properly shifts the partial flags bitfield for all modules following the HDF5 module on pre 3.2.0 logs so the flags are properly up-converted.
=> BUG: logutils up-conversin of partial_flags is broken for darshan versions prior to 3.2.0

.cirrus.yml, .github/workflows/main_ci.yml, darshan-util/pydarshan/darshan/tests/test_plot_dxt_heatmap.py, darshan-util/pydarshan/pyproject.toml
* Fixes #479
* `test_adjust_for_colorbar()` has been failing with `matplotlib >= 3.5.0` for almost a year now, which is pretty annoying because building old versions of `matplotlib` with more recent Python versions can be painful (there is no binary sometimes)
* since I don't see any actual problems with the heatmap/colorbar layouts with the newer matplotlib, add a
[PEP440](https://peps.python.org/pep-0440/)-compliant version conditional inside `test_adjust_for_colorbar()` that uses a different colorbar coordinate value with newer versions of `matplotlib`; I think it is encouraging that the new values are offset by the same value (`0.3`) as the old ones; I don't think it is worth trying to figure out which `matplotlib` commit changed the coord layout values, but we could probably do that …
=> MAINT: unpin matplotlib

darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py
* remove an extraneous step from `get_heatmap_df()`;
there should never be a fractional bin occupancy greater
than 1 achieved by multiplying fractions
* this is performance neutral on our benchmark suite:
`asv continuous -e -b ".*heatmap.*" main treddy_simplify_get_heatmap`,
and also doesn't help with producing html report faster for the
`e3sm_io_heatmap_and_dxt..` and `snyder_acme..` log files
* so, this isn't much of a victory unfortunately apart from -1 LOC;
I did make various attempts in the last two days to simplify
the algorithms here, and while I do have some branches with ~10-15 less
LOC, they take performance hits, so not ready to propose those yet
* one interesting observation is that `np.digitize` basically gives
us the same information as `pd.get_dummies(pd.cut())`, which
we …
=> MAINT: simplify get_heatmap_df()

darshan-util/darshan-logutils.c, darshan-util/darshan-logutils.h, darshan-util/pydarshan/darshan/backend/api_def_c.py, darshan-util/pydarshan/darshan/backend/cffi_backend.py
* this achieves identical memory leak improvements as gh-813 without touching any of our existing util C API functions (300 MB -> 150 MB footprint for the same benchmark test as there)
=> BUG: memleak fix CFFI only pt1

darshan-util/pydarshan/darshan/backend/cffi_backend.py
* this achieves the same 3.5 GB memory reduction as gh-815 without touching
our current C API functions
* this should be reviewed after gh-816, at which point this will simplify to
a 1-line patch in the CFFI backend module
=> BUG: fix mount memleak (CFFI only)

darshan-util/pydarshan/darshan/backend/cffi_backend.py
* this should be reviewed after gh-816, and fixes
the residual memory leak there so that we get
a flat memory profile with repeated calls
to `log_get_generic_record()`; after rebasing, this PR
should simplify to a few CFFI backend changes to free
`buf[0]` in a few places and make explicit copies for NumPy
where it is pointing to the dropped memory buffer
* note that `RUNTIME` heatmap doesn't seem to like
the extra `free()`, it causes some testing issues,
so I've excluded that here--hopefully that module
just doesn't have the same problem..
Gradual mem spike -> flat profile:
=> BUG: memleak part 3 (CFFI only)

.github/workflows/main_ci.yml
Fixes #795 as well
* Python `3.11.0rc2` is not only API stable with the final release coming in a few weeks, but is also guaranteed ABI stable: https://www.python.org/downloads/release/python-3110rc2/
* let's start testing it in our CI--many upstream projects are already providing pre-built `3.11` binaries on PyPI (`pandas`, `numpy`, `matplotlib`..)
* the run time for this new job using `act` locally seems to be about 10 minutes, which is reasonably in line with the other Python version jobs I'd say
=> TST: Python 3.11

darshan-util/darshan-logutils.c, darshan-util/pydarshan/darshan/backend/cffi_backend.py
* `dup()` returned record name and destroy the name record hash table and all associated memory in functions `darshan_log_get_name_records()` and `darshan_log_get_filtered_name_records()`
* free allocated array of record_id,record_name tuples passed back from above functions in CFFI backend
* free individual record names passed back frome above functions in CFFI backend
Fixes #824
=> BUG: memleak part 4

darshan-runtime/lib/darshan-hdf5.c, darshan-runtime/lib/darshan-lustre.c, darshan-runtime/lib/darshan-mdhim.c, darshan-runtime/lib/darshan-mpiio.c, darshan-runtime/lib/darshan-pnetcdf.c, darshan-runtime/lib/darshan-posix.c, darshan-runtime/lib/darshan-stdio.c, darshan-test/python_mpi_scripts/runtime_prog_issue_786.py, darshan-test/python_runtime_tests.py
Darshan's ability to instrument forked processes was broken by some optimizations to the module registration code path that were  applied as part of #703.
This PR includes fixes to each module that resets the module's `runtime_init_attempted` flag at module `cleanup()` time. If this flag isn't reset, then modules can not be re-initialized after they have shut down -- Darshan's fork handling relies on this ability to cleanup and re-initialize modules and was leading to fork children not being able to register records in the Darshan log.
Additionally, this PR includes a regression test to detect whether this functionality is broken again going forward.
[WIP tag while I fine tune the regression test]
=> BUG: Fix handling of forked processes in darshan-runtime

.github/workflows/main_ci.yml, darshan-util/pydarshan/darshan/experimental/plots/data_access_by_filesystem.py
* when using latest stable `matplotlib` our testsuite produces hundreds of warnings like this (example log from gh-819 :https://github.com/darshan-hpc/darshan/actions/runs/3137604371/jobs/5095963509) :
```
tests/test_data_access_by_filesystem.py: 54 warnings
tests/test_summary.py: 99 warnings
/home/tyler/python_310_darshan_venv/lib/python3.10/site-packages/darshan/experimental/plots/data_access_by_filesystem.py:536:
MatplotlibDeprecationWarning: The join function was deprecated in
Matplotlib 3.6 and will be removed two minor releases later.
ax_filesystem_counts.get_shared_x_axes().join(ax_filesystem_counts,
list_count_axes[row - 1])
```
* this originates from this upstream PR: https://github.com/matplotlib/matplotlib/pull/21584
* turn this warning into an error in our CI, to prevent …
=> MAINT: mpl join() deprecation

.github/workflows/main_ci.yml, .github/workflows/runtime_ci.yml
* based on discussion with Shane, apparently we no longer need to use `--enable-shared` because shared libs are built by default in the "new" build system
* I believe Shane will clean up some docs related to this, like here:
https://www.mcs.anl.gov/research/projects/darshan/docs/darshan-util.html
=> CI: remove shared flag

.github/workflows/main_ci.yml, darshan-util/pydarshan/darshan/tests/test_summary.py, darshan-util/pydarshan/mypy.ini
* discussed a bit with Shane--this allows the test suite to pass with a few skipped tests if a user doesn't have `lxml` installed--I think the 10 extra skips aren't so bad that all value is lost with the pared down testing in this case
* if you run `python -m pytest --pyargs darshan -n 10 -rsx` without and with `lxml` present on this branch you'll get these results respectively:
- `463 passed, 10 skipped, 2 xfailed in 109.11s (0:01:49)`
- `473 passed, 2 xfailed in 109.02s (0:01:49)`
The verbose output will show a bit more detail:
```
SKIPPED [3] ../home/tyler/python_310_darshan_venv/lib/python3.10/site-packages/darshan/tests/test_summary.py:347: Test requires lxml
SKIPPED [7] ../home/tyler/python_310_darshan_venv/lib/python3.10/site-packages/darshan/tests/test_summary.py:459: Test …
```
=> MAINT, TST: lxml optional skip

.github/workflows/main_ci.yml
* turn on `make check` in CI to run the `darshan-util` unit tests Phil added in gh-677 -- they run very quickly so I don't see why we shouldn't just run them
* we could eventually turn on `gcov` to show which lines are being traced through in the C code, but that's a bit more work to fuse into the Python cov report, so delaying that for now...
=> CI: test darshan-util

.github/workflows/main_ci.yml
* Python 3.11 final release/stable release is out now, so use it in CI
=> CI: use 3.11 final release

.github/workflows/main_ci.yml, darshan-util/pydarshan/darshan/cli/summary.py
* switch to `DYLD_FALLBACK_LIBRARY_PATH` for `pydarshan` shared library searching on MacOS in GitHub actions
* note that we're already doing this for the M1 Mac testing in Cirrus CI, and I need it locally as well on newer versions of MacOS
* we'll see if CI agrees with my assessment (I don't know all the technical details for justification..)
=> CI: try to fix MacOS CI

darshan-runtime/lib/darshan-core.c
These 2 APIs contain an argument of type MPI_Datatype.
```c
static void darshan_core_reduce_min_time(
void* in_time_v, void* inout_time_v,
int *len, MPI_Datatype *datatype);
static void darshan_core_reduce_max_time(
void* in_time_v, void* inout_time_v,
int *len, MPI_Datatype *datatype);
```
=> bug fix: when MPI is disabled

.github/workflows/build_wheels.yml
bump to v2.11.2
note there's also a typo fix in current path inclusions (forgotten `*`), as well as addition of a new inclusion for updates to the build wheels workflow file
=> CI: bump cibuildwheel to newest release

darshan-util/pydarshan/darshan/tests/test_cffi_misc.py, darshan-util/pydarshan/darshan/tests/test_data_access_by_filesystem.py, darshan-util/pydarshan/darshan/tests/test_heatmap_handling.py, darshan-util/pydarshan/darshan/tests/test_plot_common_access_table.py, darshan-util/pydarshan/darshan/tests/test_plot_dxt_heatmap.py, darshan-util/pydarshan/darshan/tests/test_plot_exp_common.py, darshan-util/pydarshan/darshan/tests/test_plot_io_cost.py, darshan-util/pydarshan/darshan/tests/test_report.py, darshan-util/pydarshan/darshan/tests/test_summary.py
Fixes #851
* the testsuite now always uses `DarshanReport` with a context manager to avoid shenanigans with `__del__` and garbage collection/`pytest`/multiple threads; another bonus is that this avoids constructing `DarshanReport` objects in `pytest` parameters, which would explain why reports were being built up during collection stage before we even start running (which, if you add CFFI into the mix, may be asking for trouble)
* this appears to fix the problem with testsuite hangs described in gh-839 and gh-851; I pushed this commit into gh-839 recently so if the CI there stops hanging with `3.10` on top of my local confirmation, hopefully we're good to go on this annoyance
* if the fix is confirmed by the CI over there, I do suggest we encourage the use of `DarshanReport` with a …
=> BUG: fix pytest hang/lock

.github/workflows/runtime_ci.yml, darshan-test/python_runtime_tests.py
* builds a non-MPI version of darshan-runtime
* adds MPI and non-MPI versions of existing runtime CI tests for forked processes
=> CI: add non-MPI test case

darshan-util/pydarshan/README.rst, darshan-util/pydarshan/docs/install.rst, darshan-util/pydarshan/docs/usage.rst
* cleanup some usage of "pydarshan" (for either "darshan" or "PyDarshan")
* cleanup docs usage of Darshan report objects to use context managers
=> DOC: fixup pydarshan docs

darshan-runtime/lib/darshan-pnetcdf-api.m4, darshan-runtime/lib/darshan-pnetcdf.c
* various put/get API calls were all using the ncid rather than the varid to retrieve variable records
=> BUG: fix bug causing misattribution of pnetcdf_var i/o

.github/workflows/main_ci.yml
* the Github Actions infrastructure is progressively phasing in a newer base image of Ubuntu:
https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
* that means that we are somewhat randomly going to see images that lack Python `3.6` from the build cache sometimes per:
https://github.com/actions/setup-python/issues/355#issuecomment-1335042510
* instead of pinning to an old version of Ubuntu in GHA for 3.6 support, let's just drop 3.6 from the testing matrix per:
https://github.com/darshan-hpc/darshan/issues/510#issuecomment-1340023264 (it has been EOL for 1 year)
* there's also no reason to retain the special Python `3.10` handling where we use Ubuntu `22.04` for that case, for two reasons: 
1) `22.04` is being rolled out as the new default …
=> CI: drop 3.6 & ubuntu switch

darshan-runtime/lib/darshan-pnetcdf-api.m4
When argument filetype is MPI_DATATYPE_NULL in vard APIs, it indicates this request is of zero length. Thus we can skip updating the counters.
Failed test program:
https://github.com/Parallel-NetCDF/PnetCDF/blob/master/test/testcases/test_vard_multiple.c
=> bug fix: PnetCDF vard APIs when filetype is MPI_DATATYPE_NULL

darshan-runtime/lib/darshan-pnetcdf-api.m4
Resolve the Segmentation fault. Below are the gdb traces.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1a2aea2907 in ncmpi_put_vars_int_all (ncid=0, varid=0, start=0x19e08c0, count=0x198fbf0, stride=0x1991c00, 
buf=0x7f1a25eec010) at ./darshan-pnetcdf-api.c:11151
11151	                    common_access_vals[1+i] = count[i];
#0  0x00007f2f784f393e in ncmpi_put_vars_int_all (ncid=0, varid=0, start=0x1c7b8c0, count=0x1c2abf0, stride=0x1c2cc00, 
buf=0x7f2f7353d010) at ./darshan-pnetcdf-api.c:11153
11153	                        common_access_vals[1+i+PNETCDF_VAR_MAX_NDIMS] = stride[i];
#0  0x00007fa89f55307f in ncmpi_get_vars_int_all (ncid=0, varid=0, start=0xca38c0, count=0xc52bf0, stride=0xc54c00, 
buf=0x7fa89a58b010) at ./darshan-pnetcdf-api.c:13080
13080 …
```
=> fix index when ndims is large

.cirrus.yml
* currently our Cirrus CI job is called nothing more than `main`--let's see if we can name it something more helpful/informative for reviewers
* while I'm at it, let's see if I can use the latest MacOS M1 image from their docs:
https://cirrus-ci.org/guide/macOS/
* also, let's double check I can temporarily disable GitHub actions CI with a commit message tag in this project when we clearly don't need it like here
[skip actions]
=> CI, MAINT: Cirrus bump/naming

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py, darshan-util/pydarshan/pyproject.toml, darshan-util/pydarshan/setup.py
Fixes #510
* in the absence of Python `3.6` support, we can safely use [PEP563](https://peps.python.org/pep-0563/) delayed type evaluations and use newer NumPy type hinting machinery; disable the old mocking shims related to this
* remove an `importlib_resources` requirement for Python `3.6`; note that for testing with Python < `3.9` you still want this third-party package I think, but clearly this conditional no longer serves any purpose since we don't support `3.6`
* remove Python `3.6` from the supported list in project metadata, and include `3.10` and `3.11`, both of which are regularly tested in our CI and have wheels available on PyPI
* adjust `cibuildwheel` settings to exclude Python `3.6` from wheel builds moving forward
* adjust `setup.py`/`pyproject.toml` to error out when …
=> MAINT: more Python 3.6 cleanups

darshan-test/python_runtime_tests.py
Fixes #828
* the forked process tests were failing locally with `act -j test_runtime`
* use a more portable approach to retrieving the absolute path to the system Python
executable (compared with assuming that `python` will do)
=> TST: portable forked process test

darshan-util/pydarshan/darshan/experimental/plots/plot_io_cost.py, darshan-util/pydarshan/darshan/tests/test_plot_io_cost.py
Fixes #881
* rotate the x axis tick labels by 90 degrees counterclockwise in the I/O cost plot to avoid
label overlap
* add regression test for x axis tick label positions/rotations/content, including for the
exact log in the matching issue and for one other log
Samples of adjusted plots:
- `shane_ior-PNETCDF_id438100-438100_11-9-41525-10280033558448664385_1.darshan`
- `imbalanced-io.darshan`
=> MAINT: I/O cost label spacing

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/experimental/plots/plot_io_cost.py, darshan-util/pydarshan/darshan/tests/test_plot_io_cost.py
Fixes #860
* include `PNETCDF_FILE_F_WAIT_TIME` in the I/O cost plot in the Python summary reports, along with regression testing and caption changes
* I would have felt more comfortable if the issue pointed me to a log file with prominent non-zero wait times, because all-zero values will also be the default for the `Wait` category when it isn't valid (even when `PNETCDF` is not used); I mostly decided not to exclude the category when `PNETCDF` is absent because it was easier to code + accounted for in the caption adjustment anyway
* I'll provide some samples of the new I/O cost plots--note that the x label squishing is handled separately in gh-883.
- `shane_ior-PNETCDF_id438100-438100_11-9-41525-10280033558448664385_1.darshan`
- `imbalanced-io.darshan`
=> ENH: WAIT_TIME in Python summary

darshan-util/pydarshan/pyproject.toml
Fixes #887
* this allows `pip install -e .` to produce a working editable install locally
* the basis for the `setuptools` pin here is based on reading through https://github.com/pypa/setuptools/issues/3548; in short, looks like a behavior change in `setuptools` so let's just pin it for now
* since this only affects Python **developers** for our project I've not added any "regression test"/"CI test" for it, but feel free to add one editable job to the CI if you want
=> BLD: fix editable installs

.github/workflows/main_ci.yml
Address new CI failures popping up in #886 related to a recent release of mypy by pinning for now.
=> CI: pin to mpy<1.0.0

darshan-util/pydarshan/darshan/backend/api_def_c.py, darshan-util/pydarshan/darshan/backend/cffi_backend.py, darshan-util/pydarshan/darshan/tests/test_cffi_misc.py
* add a per-record converter from DataFrame to darshan-util C record format that passes tests for single records (rows) with `counters` and `fcounters` (but not `rank` & `id` yet)
* add a full df->multi-record converter; this one still leads to segfaults with the C inject func with stuff like (probably corrupted data..):
```
../darshan-logutils-accumulator.c:145: darshan_accumulator_inject: Assertion `rank < acc->job_nprocs' failed.`
```
* one of the two added tests passes, the other xfails, feel free to push in fixes
* as discussed in meeting earlier today (Rob R. seems to agree), this likely shouldn't be a long-term solution--just temporary until we can hoist all analysis infrastructure to the Python level
* some of the accumulator API prototypes are copied in here from other PRs for …
=> WIP, ENH: add df->rec converter

darshan-test/regression/cray-module-alcf/env.sh, darshan-test/regression/cray-module-nersc/env.sh, darshan-test/regression/cray-module-olcf-crusher/env.sh, darshan-test/regression/cray-module-olcf-crusher/runjob.sh, darshan-test/regression/cray-module-olcf-crusher/slurm-submit.sl, darshan-test/regression/run-all.sh, darshan-test/regression/test-cases/access-size-counter-test.sh, darshan-test/regression/test-cases/cxxpi.sh, darshan-test/regression/test-cases/fperf-f77.sh, darshan-test/regression/test-cases/fperf-f90.sh, darshan-test/regression/test-cases/fprintf-fscanf-test.sh, darshan-test/regression/test-cases/mpi-io-test-dxt.sh, darshan-test/regression/test-cases/mpi-io-test.sh, darshan-test/regression/test-cases/src/cxxpi.cxx, darshan-test/regression/test-cases/stdio-test.sh, darshan-test/regression/workstation-cc-wrapper/env.sh, darshan-test/regression/workstation-ld-preload/env.sh, darshan-test/regression/workstation-profile-conf-dynamic/env.sh, darshan-test/regression/workstation-profile-conf-static/env.sh
In addition to the new system environment, this commit has 2 additional changes:
- cxxpi test case has been updated to stop using C++ MPI bindings, as these were causing compile failures and are apparently no longer in the standard
- regression test script was updated to allow input Darshan install prefix specifications like `darshan_runtime_install:darshan_util_install` (rather than a single install prefix for both) to support cases where both components aren't installed in one spot (e.g., with Spack)
=> add OLCF Crusher regression testing env

darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/tests/test_summary.py
Detect empty logs, embed a warning in the report, and bail on typical report generation.
Fixes #845.
I won't close #734, as that issue is more tied to the underlying plotting routine throwing the error (plot_io_cost), which I haven't addressed here. I'm hesitant to fix there as it's possible we refactor those routines in the future, so just trying to keep things simple.
In the mean time, this should allow PyDarshan job summary to do something sensible for empty logs.
=> ENH: PyDarshan job summary print warning and bail on logs with no data

darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py
Fixes #909
* make the library compatible with both `pandas 1.5.x` and `pandas 2.0.0rc0` by pinning the dtype we use for one-hot encoding our heatmap data
* see related upstream comment and release notes (`get_dummies()` change):
- https://github.com/pandas-dev/pandas/pull/48022#issuecomment-1448755561
- https://pandas.pydata.org/pandas-docs/version/2.0/whatsnew/v2.0.0.html
=> MAINT, BUG: pandas 2.0 compatibility

darshan-runtime/lib/darshan-hdf5.c
According to [HDF5 Doc](https://docs.hdfgroup.org/hdf5/develop/group___h5_i.html#title5), the identifier returned by `H5Iget_file_id` needs to be released using `H5Fclose`. 
This fix darshan-hpc/darshan#906
=> Fix HDF5 reference issue.

darshan-util/pydarshan/darshan/discover_darshan.py
- prefer library discovery method based on wheels, since these are shipped with their own libraries that should be used over other Darshan installs (e.g., Darshan installs provided by a facility)
- fix pkg-config based library discovery, originally mentioned in #383 
- `--path` does not seem to be a valid `pkg-config` option, but we can extract the `prefix` variable from the file as I have done here
=> MAINT: darshan-util library discovery changes for pydarshan

darshan-util/pydarshan/darshan/experimental/plots/heatmap_handling.py, darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py
* Fixes #914
* use a new `max_time` argument to compensate for the fact that DXT records are not guaranteed to encompass the wallclock duration of an instrumented runtime
* I could probably use help developing a suitable regression test, that seems a bit tricky without i.e., adding the connected log + reconstituting the plot binary data from the HTML and then parsing that somehow (certainly doable, but annoying)
* could also add a test for usage of `get_heatmap_df()` with/without the new argument for a case where it matters, though that doesn't directly guard against the regression in question
Pertinent part of updated report:
=> BUG: set DXT heatmap limit

.cirrus.yml, .github/workflows/main_ci.yml
* see drama here: https://about.codecov.io/blog/message-regarding-the-pypi-package/
* I think we should just be able to delete the `codecov` PyPI install and use their GHA plugin at this point, but I'll let CI confirm...
=> CI: deal with codecov yank

darshan-util/pydarshan/darshan/cli/style.css, darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/experimental/plots/data_access_by_filesystem.py, darshan-util/pydarshan/darshan/experimental/plots/plot_access_histogram.py, darshan-util/pydarshan/darshan/experimental/plots/plot_io_cost.py, darshan-util/pydarshan/darshan/experimental/plots/plot_opcounts.py, darshan-util/pydarshan/darshan/lib/accum.py, darshan-util/pydarshan/darshan/tests/test_data_access_by_filesystem.py, darshan-util/pydarshan/darshan/tests/test_plot_exp_common.py, darshan-util/pydarshan/darshan/tests/test_summary.py
See #910 for more details.
This PR currently has fixes for:
- Captions are hard to read (light colored text, also italicized)
-  Add "% runtime" y-axis label to right-side of I/O cost plot
-  Offset autolabeling text at 45 degrees in access size histogram plot and POSIX access pattern plot as is done in I/O op count graph
-  Don't autolabel 0 values to further help with cluttering of plots
- add a forgotten space to our warning string when a log has no data
=> PyDarshan job summary cleanup fixes

darshan-runtime/lib/darshan-core.c
The Darshan library is currently setting fork handlers near the beginning of its initialization routine -- notably, before we detect whether the app should be excluded from Darshan instrumentation (via new APP_EXCLUDE setting). These fork handlers expect Darshan library state to be initialized properly, but that clearly does not happen if the app is excluded (there is no Darshan library state in this case). This is currently leading to crashes for this scenario (excluded app that calls fork).
To fix, don't set Darshan fork handlers until it's known that library initialization succeeded.
=> BUG: fix potential segfault with apps that `fork()` and use Darshan app exclusions

darshan-util/pydarshan/darshan/backend/cffi_backend.py, darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/experimental/plots/__init__.py, darshan-util/pydarshan/darshan/experimental/plots/plot_posix_access_pattern.py, darshan-util/pydarshan/darshan/tests/test_lib_accum.py, darshan-util/pydarshan/darshan/tests/test_summary.py
See commits for more details.
If things look good, I can add some tests that can at least check some expected `summary_record` counter values returned by `acummulate_records()`.
A few thoughts:
- This is the first plotting routine that takes a dataframe as input (others take a report object). I thought about this a bit, and think it would be good to generalize the plotting routines we provide away from report objects, to allow us to plot data coming from multiple log files. I didn't modify any other plotting routines, but could take a pass at this in another PR if that seems reasonable?
- Related to above, but this new plotting routine is hardcoded to get plot data from the first row of the input dataframe for now. That works fine for the accumulator use case obviously since it's just a …
=> WIP, ENH: add POSIX access pattern plot to darshan job summary

darshan-runtime/configure.ac, darshan-runtime/doc/darshan-runtime.txt, darshan-runtime/lib/darshan-core.c
This should address a longstanding issue with Darshan not always being able to determine the username associated with a job on Cray systems that use Slurm. Specifically, when Slurm users use the `--export` option to `srun` to set additional environment variables, this can wipe out env vars like `LOGNAME`, which Darshan uses to determine the associated username with a job.
This new configure option allows users to specify additional env vars that can be considered for determining a job's username (e.g., `SLURM_JOB_USER`). If specified, Darshan will consider this provided env var _first_.
In my testing on NERSC Cori, this is all working as expected:
- if this new config option is not specified, Darshan can not determine the username if the user uses the `--export` option to `srun`
- if this …
=> ENH: add darshan-runtime configure option for specifying a username env var

darshan-util/pydarshan/README.rst, darshan-util/pydarshan/docs/index.rst, darshan-util/pydarshan/docs/install.rst, darshan-util/pydarshan/docs/usage.rst
Some users have pointed out that PyDarshan docs are stale, example code snippets aren't working, etc. I suspect it's been awhile since this has been updated and we've obviously been making lots of changes to the code so this isn't particularly surprising.
I made a general pass over the PyDarshan docs to make sure they are clear, up-to-date, and to make sure examples provided are functional. Commit messages detail a little more explicitly what has changed. I tried to shift almost all of the text related to installation/usage into the standalone pages to avoid duplicating too much between those and the `README.rst`.
=> DOC: PyDarshan doc improvements

darshan-util/pydarshan/darshan/cli/base.html, darshan-util/pydarshan/darshan/cli/style.css, darshan-util/pydarshan/darshan/cli/summary.py, darshan-util/pydarshan/darshan/lib/accum.py, darshan-util/pydarshan/darshan/tests/test_lib_accum.py, darshan-util/pydarshan/darshan/tests/test_summary.py
I tried to accomplish a couple of goals here:
1. Force specific module figures to always appear in the same location  for each module.
2. Add a simple overview table for modules that support accumulation that replaces the performance estimate string.
Without 1), our current CSS grid for module data just packs 2 figures to a row without any real mechanisms to control how many figures can go on a line, which figures can be positioned side-by-side, etc. Figures are currently added in the order they are registered in the summary code, but different modules have different number of figures so there's not really a simple way to ensure figure organization is uniform across modules.
To help with this, I quickly adopted some CSS code to more explicitly place module figures in a fixed grid. The …
=> ENH: reorganize PyDarshan summary reports and add an overview table

darshan-util/pydarshan/README.rst
Usage of `ref` for linking to other pages is problematic for uploading our README using twine, so I'll just remove those snippets to avoid problems.
=> DOC: simplify PyDarshan README for upload using twine

.github/workflows/runtime_ci.yml
* Fixes #950
* looks like `h5py` from-source build is struggling with the recently-released Cython `3.0.0`, so let's see if pinning to older Cython series helps get CI green for now
=> CI: pin Cython in runtime job

darshan-runtime/lib/darshan-core.c
The shared reduction callback for the heatmap module is used to reach a consistent heatmap format across all ranks at shutdown time, which our analysis tools expect.
Furthermore, a "shared reduction" doesn't really apply to heatmap data, as it's already captured on every process (as opposed to a shared record on rank 0) -- ignoring the disable shared reduction flag is not an issue for the heatmap module, making this an easy fix.
Fixes #941
=> BUG: never disable "shared reductions" for heatmap mod

darshan-util/darshan-heatmap-logutils.c, darshan-util/darshan-logutils.h
This is the utility side counter part to #942.
This will "repair" logs on the fly that were generated under the conditions described in https://github.com/darshan-hpc/darshan/issues/941 so that the heatmap bin count stays uniform/rectangular despite slight timing skew across ranks.  This condition is only possible for logs generated with Darshan 3.4.3   with shared record reduction explicitly disabled.
@nafi3 are you able to confirm if you can parse existing logs that have mismatched heatmap bin problems?  (not the negative value problem; that is something different).
Fixes #941
=> logutils workaround for heatmap time skew

.github/workflows/main_ci.yml, darshan-util/pydarshan/RELEASE-CHECKLIST-PyDarshan.txt, darshan-util/pydarshan/darshan/experimental/plots/data_access_by_filesystem.py, darshan-util/pydarshan/darshan/experimental/plots/plot_io_cost.py, darshan-util/pydarshan/darshan/tests/test_summary.py, darshan-util/pydarshan/pyproject.toml, darshan-util/pydarshan/setup.py
* a few adjustments to `pyproject.toml` to allow for `pip install -v .` followed by `python -m pytest --pyargs darshan -n 32` to pass the full suite locally on x86_64 Linux with Python `3.12.0rc3`, given that the final release of Python `3.12.0` is about a week away I think
* changing the version of `setuptools` may break the developer experience with "editable" installs, since I recall pinning it a while back for that reason, but I think supporting isolated wheel builds/install with `3.12.0` should likely take priority
* some of the metadata updates to `pyproject.toml` are apparently newly-required fields that must be present (`pip install -v .` fails otherwise)
* perhaps we can delay adding `3.12` to the CI testing until the final release, though GHA does have the RC available if we …
=> MAINT: 3.12 support

.github/workflows/main_ci.yml, darshan-util/pydarshan/benchmarks/asv.conf.json
Temporary workaround for issue mentioned by @tylerjereddy in #972.
=> CI, BENCH: pin seaborn to avoid namespace issues with asv

darshan-runtime/configure.ac, darshan-runtime/lib/darshan-stdio.c, darshan-runtime/share/ld-opts/darshan-stdio-ld-opts.in
A long time ago we added a wrapper and an autoconf test for the `__isoc99_fscanf` function that can be found in newer glibc implementations. It doesn't appear as though this old autoconf test appropriately tests whether we should include a wrapper for the `__isoc99_fscanf` routine. Locally, this autoconf test was failing even though I have `__isoc99_fscanf`, leading to missed instrumentation of these calls.
We can't simply offer wrappers for both `fscanf` and `__isoc99_fscanf`, as this leads to symbol redefinition errors when building Darshan's shared library.
This PR tries to address the issue by detecting the presence of `__isoc99_fscanf`, and including a wrapper for that call if found. If not found, we include our traditional `fscanf` wrapper. The key is to ensure that only one of …
=> BUG: fix handling of `fscanf`/`__isoc99_fscanf`

.github/workflows/end_to_end_regression_polaris.yml
Uses: https://github.com/marketplace/actions/trigger-gitlab-ci-through-webhooks
=> CI: new workflow for triggering ALCF GitLab CI on Polaris

darshan-runtime/configure.ac, darshan-runtime/doc/darshan-runtime.txt, darshan-runtime/lib/darshan-core-init-finalize.c
Python apps using the `multiprocessing` package can invoke the `_exit()` call directly. E.g., see [this code](https://hg.python.org/cpython/file/e04cd497aa41/Lib/multiprocessing/popen_fork.py#l76).
Invoking `_exit()` directly bypasses Darshan's shared library destructor, which is what is used to write out its log file. So, these processes spawned by `multiprocessing` are properly instrumenting I/O calls, but never get an opportunity to write the instrumentation data to log file. 
This PR adds a function wrapper for `_exit()`, which Darshan uses to intercept `_exit()` calls, invoking the Darshan shutdown procedure before calling the real _exit implementation. This modification to Darshan seems to fix some issues reported by users related to this issue (e.g., #872). Let's see if it can get …
=> ENH: wrap _exit in Darshan's shared library

.github/workflows/darshan_ldms_test_ci.yml
@shanedsnyder Turns out this was a known issue that has since been fixed. The ``ldmsd`` command was modified to run as a background process when executed so a ``&`` needed to be added at the end of this command.
Also, I removed a line of workaround code as it's no longer needed. :)
=> Fix for LDMS CI Workflow

darshan-util/doc/darshan-util.txt
The documentation seems to refer to some STDIO counters with a slightly different name than the ones shown in the parsers.
=> fix STDIO counter names in documentation

darshan-util/pydarshan/RELEASE-CHECKLIST-PyDarshan.txt, darshan-util/pydarshan/docs/usage.rst
This PR adds a link to an example PyDarshan job summary HTML report to our docs, and adds a note to the release checklist to consider updating the example report as new features are added.
You can view the example report here: https://www.mcs.anl.gov/research/projects/darshan/docs/example_report.html
=> DOC: add link to an example PyDarshan report in docs

darshan-util/darshan-logutils.c
In some cases if zlib-ng is used as the gzip library for Darshan, it will indicate that the correct number of bytes were decompressed, but will also modify some bytes in the buffer beyond that point.  In the Darshan this specifically can produce a corrupted mount table by appending erroneous characters onto the string data.
Fixes #995
=> add workaround for potential zlib-ng problem

.github/workflows/darshan_ldms_test_ci.yml
This fixes the  libjansson error that was occurring when installing the LDMS from top of tree:
```checking for libjansson... no
configure: error: libjansson or jansson.h not found
```
=> Darshan-LDMS Workflow Patch

darshan-runtime/lib/darshan-core.c
- this should make the log format slightly more robust with respect to how the data is decompressed, but does not require any file format change
- protects against problems like #1002, but would only be effective for newly written logs
=> write trailing null byte in mnt table

darshan-runtime/lib/darshan-config.c
Various Darshan config variables take a CSV of regexes as input (e.g. APP_EXCLUDE, NAME_EXCLUDE). Darshan's code for iterating and parsing these regexes can cause an infinite loop if one of the regexes is unable to be compiled. E.g.,
```
NAME_EXCLUDE    *    POSIX
```
The 2nd field is the regex CSV (in this case just a single regex), but `*` is not a valid regex (it is a special character indicating that the preceding character(s) are repeated one or more times, but there are no preceding characters above) and causes an error when compiling the regex. This input causes Darshan to continuously output the following warning:
```
darshan library warning: unable to compile Darshan config NAME_EXCLUDE regex *
```
This PR fixes the bug causing the Darshan library to continuously parse the same …
=> BUG: fix darshan-runtime config parsing leading to infinite loops

darshan-runtime/lib/darshan-ldms.c, maint/config/check_ldms.m4
This patch adds a check for the ``ldms_xprt_new_with_auth`` function in LDMS Streams API. There are currently two versions of this function (one takes three arguments and the other takes four) depending on the LDMS library version. The purpose of this patch is to prevent any build errors caused by version incompatibilities for users wanting to enable LDMS. 
Please let me know if there are issues with these changes.
=> Patch for ldms streams function 

darshan-runtime/configure.ac, darshan-util/configure.ac, maint/config/check_bzlib.m4
We've gotten reports of strange errors when configuring `darshan-util` with APMPI support with newer autoconf versions (e.g., 2.72). I could not make sense of the errors, but there were lots of warnings about usage of deprecated functions, so I went ahead and fixed all of those here. Not exactly sure how, but it does seem to have resolved the weird configure error we're getting. Tested using autoconf 2.69 and 2.72 and things all seems good, but let's see how CI goes.
=> MAINT: stop using deprecated autoconf functions

.github/workflows/darshan_ldms_test_ci.yml, maint/config/check_ldms.m4
Wrong header file included in the patch from PR #1009.
=> LDMS: fixing lib include

darshan-util/darshan-convert.c
- independent obfuscation flags to allow more control over what is obfuscated (e.g., to not obfuscate job ids)
- don't obfuscate common names like standard streams (e.g., <STDOUT>) or heatmaps
=> ENH: various darshan-convert obfuscate fixes

darshan-util/pydarshan/darshan/cli/file_stats.py, darshan-util/pydarshan/darshan/cli/job_stats.py, darshan-util/pydarshan/darshan/tests/test_file_stats.py, darshan-util/pydarshan/darshan/tests/test_job_stats.py, darshan-util/pydarshan/darshan/tests/test_report.py, darshan-util/pydarshan/darshan/tests/test_summary.py, darshan-util/pydarshan/docs/usage.rst, darshan-util/pydarshan/pyproject.toml
Based on original PR from @Yanlilyu in #954.
Key enhancements are as follows:
- lots of new statistics/metadata printed
- support for pretty printing via Rich package (default) or output in CSV format for subsequent analysis
- support for PyDarshan name filtering from #1017 
- parallelization using ProcessPoolExecutor
- optional manifest file to support massive amounts of log file input (to avoid command line limits)
- in-depth testing to exercise various options as part of our CI
- updated docs to describe usage of these 2 new tools
See docs/usage.rst for details on command line tool options.
=> ENH: new PyDarshan CLI tools for job/file stats for many logs

.github/workflows/build_wheels.yml
The `upload-artifact` version we had been using is now deprecated. 
Note that there are changes in the new version that don't allow multiple workflow steps to combine their output into a single artifact archive. Changes have been made to direct output from each step into unique archives, along with a new phase of the workflow that merges all of these together into a single artifact.
=> CI: update upload-artifact version in build-wheels workflow

.github/workflows/end_to_end_pytest.yml
Looks like using the default version of setuptools solves the issue of #1040.
Now the github action job of end_to_end_pytest.yml passed.
=> Github action: remove setuptools version constrain

darshan-util/pydarshan/mypy.ini
* Mirror the upstream change to disable this plugin. For details, see:
https://github.com/scipy/scipy/pull/23123
* I don't think we're running `mypy` in CI anyway, but might as well clean it up in case the team
turns it on at some point (a well-maintained type stub library now exists upstream: https://github.com/numpy/numtype).
=> TYP: Disable NumPy's deprecated mypy plugin

conf.py, darshan-runtime/doc/darshan-runtime.rst, readthedocs/_static/css/custom.css
Trying to see if a custom css can be used to help with #1044
=> experimenting with modifying css for table

darshan-util/pydarshan/darshan/backend/cffi_backend.py
When generating summary report from the Darshan logs containing DAOS module data, derived metrics like total_read_volume_bytes and total_write_volume_bytes were displaying incorrect values. 
The issue was the pydarshan.backend.cffi_backend._df_to_rec utility function. It was using an incomplete NumPy dtype with missing several fields from the darshan_daos_object C struct (pool_uuid, cont_uuid, oid_hi, and oid_lo) when converting DAOS records to a C buffer of records that is consumed by the Darshan-util C code. Similar problem exists for the DFS module data.
This PR fixes the issue by updating the np.recarray dtype in _df_to_rec to include all fields for DAOS and DFS records.
=> BUG: correct DAOS and DFS layout in dataframe repacking that is consumed by the logutils accumulator API

darshan-runtime/configure.ac, darshan-runtime/doc/darshan-runtime.rst
Test CI to see if making mmap I/O the default.
=> Change mmap I/O default mode to enable

darshan-runtime/configure.ac, darshan-runtime/darshan-config.in
This PR is to enable `darshan-config` utility program to show all configured options used when Darshan is built.
Below are the changes when using this configure command:
```
../darshan/configure --prefix=$HOME/Darshan/DEV \
--with-jobid-env=NONE \
--with-log-path=$HOME/Darshan/LOG \
--with-log-path-by-env=DARSHAN_LOG1,DARSHAN_LOG2 \
-                     -with-mod-mem=64 \
--with-name-mem=16 \
--with-username-env=JOHNDOE \
--with-zlib=$ZLIB_DIR \
--silent \
--enable-pnetcdf-mod --with-pnetcdf=$PNETCDF_DIR \
--enable-hdf5-mod    --with-hdf5=$HDF5_DIR \
CFLAGS="-O0 -g -Wfatal-errors -Wall" \
UTIL_CC=gcc RUNTIME_CC=cc
``` 
Command `darshan-config --all` now shows all options used at Darshan's configure time.
<details>
<summary>(click to expand)</summary>
```
This Darshan Runtime 3.4.7 was …
```
=> darshan-config: add a complete list of options configured

darshan-runtime/lib/darshan-dynamic.h, darshan-runtime/lib/darshan-mpiio.c, darshan-runtime/share/ld-opts/darshan-mpiio-ld-opts
* MPI_File_iread_all
* MPI_File_iread_at_all
* MPI_File_iwrite_all
* MPI_File_iwrite_at_all
=> Add 4 missing MPI-IO APIs

darshan-runtime/configure.ac, darshan-runtime/test/tst_runs.sh
OpenMPI 5.0.5 and priors contain a bug that can corrupt the
Darshan log files. The bug is related to file locking protocols
implemented when data sieving is enabled. Setting hint cb_nodes
to 1 can avoid the bug, but may make writing log files slow.
For more information, see PR #1070,
=> Set default MPI-IO hint cb_nodes to 1 when using OpenMPI 5.0.5 and priors

darshan-runtime/configure.ac, darshan-runtime/doc/darshan-runtime.rst, maint/config/check_ldms.m4
When Darshan is configured using `--with-pnetcdf=DIR` without
`--enable-pnetcdf-mod`, the pnetcdf module will not be built.
However, in this case, it is clear that the user's intent is to enable pnetcdf.
This PR changes the behavior to automatically sets `--enable-pnetcdf-mod`
when `--with-pnetcdf=DIR` is used at the configure time.
Same for modules HDF5, DAOS, and LDMS.
=> Setting --with-pnetcdf automatically enables enable_pnetcdf_mod

darshan-runtime/doc/darshan-runtime.rst, darshan-test/automated/build-darshan.sh, darshan-util/doc/darshan-util.rst
* `--disable-darshan-util`
* `--disable-darshan-runtime`
* `--enable-pydarshan`
* `--with-zlib=DIR`
* `--without-zlib`
* `--with-bzlib=DIR`
* `--without-bzlib`
* `--with-python-sys-prefix`
* `--with-python_prefix`
* `--with-python_exec_prefix`
Also, modify `darshan-test/automated/build-darshan.sh` to build from the root folder.
=> DOC: add missing configure options to user guides

darshan-runtime/darshan-config.in
Add the missing pnetcdf library path, which fixes the linking error below.
```
mpicc -Wall -g -O2 -I/usr/include   hello-mpiio.c   -o hello-mpiio
/usr/bin/ld: /lus/flare/projects/alcf_training/io-libraries/soft/darshan-3.5.0/lib/libdarshan.so: undefined reference to `ncmpi_inq_vardimid'
```
=> Add pnetcdf lib to --dyn-ld-flags
